.TH "Base" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBnamespace1::MyTypeInNameSpace1\fP, and \fBnamespace2::MyTypeInNameSpace2\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBase\fP (int an_x)"
.br
.ti -1c
.RI "int \fBx\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5120 of file gtest_unittest\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Base::Base (int an_x)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 5122 of file gtest_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "int Base::x () const\fC [inline]\fP"

.PP
Definition at line 5123 of file gtest_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
