.TH "ChildClassWithoutStreamOperator" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChildClassWithoutStreamOperator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParentClass\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 94 of file googletest\-printers\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
