.TH "ConstOnlyContainerWithClassIterator::const_iterator" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstOnlyContainerWithClassIterator::const_iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const int & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7301 of file gtest_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "const int& ConstOnlyContainerWithClassIterator::const_iterator::operator* () const"

.SS "\fBconst_iterator\fP& ConstOnlyContainerWithClassIterator::const_iterator::operator++ ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
