.TH "ConversionHelperBase" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConversionHelperBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBConversionHelperDerived\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 7179 of file gtest_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
