.TH "Counter" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sample4\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCounter\fP ()"
.br
.ti -1c
.RI "int \fBIncrement\fP ()"
.br
.ti -1c
.RI "int \fBDecrement\fP ()"
.br
.ti -1c
.RI "void \fBPrint\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file sample4\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Counter::Counter ()\fC [inline]\fP"

.PP
Definition at line 41 of file sample4\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int Counter::Decrement ()"

.PP
Definition at line 41 of file sample4\&.cc\&.
.SS "int Counter::Increment ()"

.PP
Definition at line 37 of file sample4\&.cc\&.
.SS "void Counter::Print () const"

.PP
Definition at line 50 of file sample4\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
