.TH "CustomStruct" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomStruct\fP (int \fBvalue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 994 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CustomStruct::CustomStruct (int value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 995 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int CustomStruct::x"

.PP
Definition at line 996 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
