.TH "DerivedTest< T >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedTest< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommonTest< T >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class DerivedTest< T >"

.PP
Definition at line 259 of file gtest\-typed\-test_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
