.TH "DogAdder" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DogAdder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDogAdder\fP (const char *a_value)"
.br
.ti -1c
.RI "\fBDogAdder\fP (const \fBDogAdder\fP &other)"
.br
.ti -1c
.RI "\fBDogAdder\fP \fBoperator=\fP (const \fBDogAdder\fP &other)"
.br
.ti -1c
.RI "\fBDogAdder\fP \fBoperator+\fP (const \fBDogAdder\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDogAdder\fP &other) const"
.br
.ti -1c
.RI "const std::string & \fBvalue\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 213 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DogAdder::DogAdder (const char * a_value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 215 of file googletest\-param\-test\-test\&.cc\&.
.SS "DogAdder::DogAdder (const \fBDogAdder\fP & other)\fC [inline]\fP"

.PP
Definition at line 216 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDogAdder\fP DogAdder::operator+ (const \fBDogAdder\fP & other) const\fC [inline]\fP"

.PP
Definition at line 222 of file googletest\-param\-test\-test\&.cc\&.
.SS "bool DogAdder::operator< (const \fBDogAdder\fP & other) const\fC [inline]\fP"

.PP
Definition at line 227 of file googletest\-param\-test\-test\&.cc\&.
.SS "\fBDogAdder\fP DogAdder::operator= (const \fBDogAdder\fP & other)\fC [inline]\fP"

.PP
Definition at line 218 of file googletest\-param\-test\-test\&.cc\&.
.SS "const std::string& DogAdder::value () const\fC [inline]\fP"

.PP
Definition at line 228 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
