.TH "DynamicFixture" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicFixture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.PP
Inherited by \fBDynamicTest< Pass >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamicFixture\fP ()"
.br
.ti -1c
.RI "\fB~DynamicFixture\fP () override"
.br
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 931 of file googletest\-output\-test_\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DynamicFixture::DynamicFixture ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 933 of file googletest\-output\-test_\&.cc\&.
.SS "DynamicFixture::~DynamicFixture ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 934 of file googletest\-output\-test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void DynamicFixture::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 935 of file googletest\-output\-test_\&.cc\&.
.SS "static void DynamicFixture::SetUpTestSuite ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 938 of file googletest\-output\-test_\&.cc\&.
.SS "void DynamicFixture::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 936 of file googletest\-output\-test_\&.cc\&.
.SS "static void DynamicFixture::TearDownTestSuite ()\fC [inline]\fP, \fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 939 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
