.TH "DynamicTest< Pass >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicTest< Pass >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDynamicFixture\fP, and \fBDynamicUnitTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestBody\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<bool Pass>
.br
class DynamicTest< Pass >"

.PP
Definition at line 945 of file googletest\-output\-test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<bool Pass> void \fBDynamicTest\fP< Pass >::TestBody ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::Test\fP\&.
.PP
Definition at line 947 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
