.TH "ExpectFailureTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpectFailureTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFailureMode\fP { \fBFATAL_FAILURE\fP, \fBNONFATAL_FAILURE\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddFailure\fP (\fBFailureMode\fP failure)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 815 of file googletest\-output\-test_\&.cc\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBExpectFailureTest::FailureMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFATAL_FAILURE \fP\fP
.TP
\fB\fINONFATAL_FAILURE \fP\fP
.PP
Definition at line 817 of file googletest\-output\-test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ExpectFailureTest::AddFailure (\fBFailureMode\fP failure)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 818 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
