.TH "FieldHelper" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmock_link_test\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldHelper\fP (int a_field)"
.br
.ti -1c
.RI "int \fBfield\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfield_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file gmock_link_test\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldHelper::FieldHelper (int a_field)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 240 of file gmock_link_test\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int FieldHelper::field () const\fC [inline]\fP"

.PP
Definition at line 241 of file gmock_link_test\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int FieldHelper::field_"

.PP
Definition at line 242 of file gmock_link_test\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
