.TH "Fixture" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fixture
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file gtest_skip_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void Fixture::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 44 of file gtest_skip_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
