.TH "FooEnvironment" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FooEnvironment
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Environment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 984 of file googletest\-output\-test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void FooEnvironment::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Environment\fP\&.
.PP
Definition at line 986 of file googletest\-output\-test_\&.cc\&.
.SS "void FooEnvironment::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Environment\fP\&.
.PP
Definition at line 988 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
