.TH "GeneratorEvaluationTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneratorEvaluationTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestWithParam< int >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBparam_value\fP ()"
.br
.ti -1c
.RI "static void \fBset_param_value\fP (int \fBparam_value\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 751 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "static int GeneratorEvaluationTest::param_value ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 753 of file googletest\-param\-test\-test\&.cc\&.
.SS "static void GeneratorEvaluationTest::set_param_value (int param_value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 754 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
