.TH "build/_deps/googletest-src/googlemock/test/gmock-spec-builders_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-spec-builders_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\-spec\-builders\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\-spi\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMethod\fP   MethodW"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Method   MethodW"

.PP
Definition at line 142 of file gmock\-spec\-builders_test\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 2592 of file gmock\-spec\-builders_test\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "MockA a_\fC [protected]\fP"

.PP
Definition at line 1329 of file gmock\-spec\-builders_test\&.cc\&.
.SS "MockB b_\fC [protected]\fP"

.PP
Definition at line 1330 of file gmock\-spec\-builders_test\&.cc\&.
.SS "LogTestHelper helper_\fC [protected]\fP"

.PP
Definition at line 2136 of file gmock\-spec\-builders_test\&.cc\&.
.SS "int value"

.PP
Definition at line 1880 of file gmock\-spec\-builders_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
