.TH "build/_deps/googletest-src/googlemock/test/gmock_output_test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock_output_test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMockFoo\fP"
.br
.ti -1c
.RI "class \fBGMockOutputTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExpectedCall)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExpectedCallToVoidFunction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExplicitActionsRunOut)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnexpectedCall)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnexpectedCallToVoidFunction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExcessiveCall)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExcessiveCallToVoidFunction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UninterestingCall)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UninterestingCallToVoidFunction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, RetiredExpectation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnsatisfiedPrerequisite)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnsatisfiedPrerequisites)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnsatisfiedWith)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnsatisfiedExpectation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, MismatchArguments)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, MismatchWith)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, MismatchArgumentsAndWith)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UnexpectedCallWithDefaultAction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExcessiveCallWithDefaultAction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, UninterestingCallWithDefaultAction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, ExplicitActionsRunOutWithDefaultAction)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, CatchesLeakedMocks)"
.br
.ti -1c
.RI "\fBMATCHER_P2\fP (IsPair, first, second, '')"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBGMockOutputTest\fP, PrintsMatcher)"
.br
.ti -1c
.RI "void \fBTestCatchesLeakedMocksInAdHocTests\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 275 of file gmock_output_test_\&.cc\&.
.SS "MATCHER_P2 (IsPair, first, second, '')"

.PP
Definition at line 256 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, CatchesLeakedMocks)"

.PP
Definition at line 239 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExcessiveCall)"

.PP
Definition at line 109 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExcessiveCallToVoidFunction)"

.PP
Definition at line 116 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExcessiveCallWithDefaultAction)"

.PP
Definition at line 210 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExpectedCall)"

.PP
Definition at line 71 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExpectedCallToVoidFunction)"

.PP
Definition at line 80 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExplicitActionsRunOut)"

.PP
Definition at line 89 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, ExplicitActionsRunOutWithDefaultAction)"

.PP
Definition at line 231 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, MismatchArguments)"

.PP
Definition at line 178 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, MismatchArgumentsAndWith)"

.PP
Definition at line 193 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, MismatchWith)"

.PP
Definition at line 186 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, PrintsMatcher)"

.PP
Definition at line 260 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, RetiredExpectation)"

.PP
Definition at line 131 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnexpectedCall)"

.PP
Definition at line 95 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnexpectedCallToVoidFunction)"

.PP
Definition at line 102 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnexpectedCallWithDefaultAction)"

.PP
Definition at line 200 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UninterestingCall)"

.PP
Definition at line 123 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UninterestingCallToVoidFunction)"

.PP
Definition at line 127 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UninterestingCallWithDefaultAction)"

.PP
Definition at line 223 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnsatisfiedExpectation)"

.PP
Definition at line 171 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnsatisfiedPrerequisite)"

.PP
Definition at line 140 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnsatisfiedPrerequisites)"

.PP
Definition at line 154 of file gmock_output_test_\&.cc\&.
.SS "TEST_F (\fBGMockOutputTest\fP, UnsatisfiedWith)"

.PP
Definition at line 167 of file gmock_output_test_\&.cc\&.
.SS "void TestCatchesLeakedMocksInAdHocTests ()"

.PP
Definition at line 265 of file gmock_output_test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
