.TH "build/_deps/googletest-src/googlemock/test/gmock-port_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-port_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (DummyTest, Dummy)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (DummyTest, Dummy)"

.PP
Definition at line 42 of file gmock\-port_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
