.TH "build/_deps/googletest-src/googlemock/test/gmock-internal-utils_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-internal-utils_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/internal/gmock\-internal\-utils\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\-spi\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'src/gtest\-internal\-inl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBproto2\fP"
.br
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGTEST_IMPLEMENTATION_\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GTEST_IMPLEMENTATION_   1"

.PP
Definition at line 56 of file gmock\-internal\-utils_test\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "std::string original_verbose_\fC [protected]\fP"

.PP
Definition at line 374 of file gmock\-internal\-utils_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
