.TH "build/_deps/googletest-src/googlemock/test/gmock-cardinalities_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-cardinalities_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gtest/gtest\-spi\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
