.TH "build/_deps/googletest-src/googlemock/test/gmock-matchers-misc_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-matchers-misc_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'test/gmock\-matchers_test\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::gmock_matchers_test\fP"
.br
.ti -1c
.RI " \fBtesting::gmock_matchers_test::matcher_test\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
