.TH "build/_deps/googletest-src/googlemock/test/gmock_stress_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock_stress_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 219 of file gmock_stress_test\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "int* count"

.PP
Definition at line 90 of file gmock_stress_test\&.cc\&.
.SS "\fBMockFoo\fP* mock_foo"

.PP
Definition at line 89 of file gmock_stress_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
