.TH "build/_deps/googletest-src/googlemock/test/gmock-actions_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-actions_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\-actions\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\-spi\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int value"

.PP
Definition at line 1714 of file gmock\-actions_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
