.TH "build/_deps/googletest-src/googlemock/include/gmock/gmock.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/include/gmock/gmock.h
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\-actions\&.h'\fP
.br
\fC#include 'gmock/gmock\-cardinalities\&.h'\fP
.br
\fC#include 'gmock/gmock\-function\-mocker\&.h'\fP
.br
\fC#include 'gmock/gmock\-matchers\&.h'\fP
.br
\fC#include 'gmock/gmock\-more\-actions\&.h'\fP
.br
\fC#include 'gmock/gmock\-more\-matchers\&.h'\fP
.br
\fC#include 'gmock/gmock\-nice\-strict\&.h'\fP
.br
\fC#include 'gmock/internal/gmock\-internal\-utils\&.h'\fP
.br
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGMOCK_DECLARE_bool_\fP (catch_leaked_mocks)"
.br
.ti -1c
.RI "\fBGMOCK_DECLARE_string_\fP (verbose)"
.br
.ti -1c
.RI "\fBGMOCK_DECLARE_int32_\fP (default_mock_behavior)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::InitGoogleMock\fP (int *argc, char **argv)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::InitGoogleMock\fP (int *argc, wchar_t **argv)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::InitGoogleMock\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "GMOCK_DECLARE_bool_ (catch_leaked_mocks)"

.SS "GMOCK_DECLARE_int32_ (default_mock_behavior)"

.SS "GMOCK_DECLARE_string_ (verbose)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
