.TH "build/_deps/googletest-src/googlemock/test/gmock_test_utils.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock_test_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgmock_test_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgmock_test_utils\&.GetSourceDir\fP ()"
.br
.ti -1c
.RI "def \fBgmock_test_utils\&.GetTestExecutablePath\fP (executable_name)"
.br
.ti -1c
.RI "def \fBgmock_test_utils\&.GetExitStatus\fP (exit_code)"
.br
.ti -1c
.RI "def \fBgmock_test_utils\&.Main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgmock_test_utils\&.Subprocess\fP = \fBgtest_test_utils\&.Subprocess\fP"
.br
.ti -1c
.RI "\fBgmock_test_utils\&.TestCase\fP = gtest_test_utils\&.TestCase"
.br
.ti -1c
.RI "\fBgmock_test_utils\&.environ\fP = gtest_test_utils\&.environ"
.br
.ti -1c
.RI "\fBgmock_test_utils\&.SetEnvVar\fP = gtest_test_utils\&.SetEnvVar"
.br
.ti -1c
.RI "\fBgmock_test_utils\&.PREMATURE_EXIT_FILE_ENV_VAR\fP = gtest_test_utils\&.PREMATURE_EXIT_FILE_ENV_VAR"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
