.TH "build/_deps/googletest-src/googlemock/test/gmock-matchers-arithmetic_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock-matchers-arithmetic_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'test/gmock\-matchers_test\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::gmock_matchers_test\fP"
.br
.ti -1c
.RI " \fBtesting::gmock_matchers_test::adl_test\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const RawType close_to_infinity_\fC [protected]\fP"

.PP
Definition at line 1112 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType close_to_negative_zero_\fC [protected]\fP"

.PP
Definition at line 1103 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType close_to_one_\fC [protected]\fP"

.PP
Definition at line 1107 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType close_to_positive_zero_\fC [protected]\fP"

.PP
Definition at line 1102 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType further_from_infinity_\fC [protected]\fP"

.PP
Definition at line 1113 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType further_from_negative_zero_\fC [protected]\fP"

.PP
Definition at line 1104 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType further_from_one_\fC [protected]\fP"

.PP
Definition at line 1108 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType infinity_\fC [protected]\fP"

.PP
Definition at line 1111 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const Bits infinity_bits_\fC [protected]\fP"

.PP
Definition at line 1099 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType max_\fC [protected]\fP"

.PP
Definition at line 1116 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const Bits max_ulps_\fC [protected]\fP"

.PP
Definition at line 1095 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType nan1_\fC [protected]\fP"

.PP
Definition at line 1119 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const RawType nan2_\fC [protected]\fP"

.PP
Definition at line 1120 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const Bits one_bits_\fC [protected]\fP"

.PP
Definition at line 1098 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SS "const Bits zero_bits_\fC [protected]\fP"

.PP
Definition at line 1097 of file gmock\-matchers\-arithmetic_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
