.TH "build/_deps/googletest-src/googlemock/src/gmock-spec-builders.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/src/gmock-spec-builders.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\-spec\-builders\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <set>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gmock/gmock\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP \fBtesting::internal::GTEST_DEFINE_STATIC_MUTEX_\fP (g_gmock_mutex)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::LogWithLocation\fP (\fBtesting::internal::LogSeverity\fP severity, const char *file, int line, const std::string &message)"
.br
.ti -1c
.RI "void \fBtesting::internal::ReportUninterestingCall\fP (CallReaction reaction, const std::string &msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP ThreadLocal< Sequence * > \fBtesting::internal::g_gmock_implicit_sequence\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* first_used_file"

.PP
Definition at line 470 of file gmock\-spec\-builders\&.cc\&.
.SS "int first_used_line"

.PP
Definition at line 471 of file gmock\-spec\-builders\&.cc\&.
.SS "::std::string first_used_test"

.PP
Definition at line 473 of file gmock\-spec\-builders\&.cc\&.
.SS "::std::string first_used_test_suite"

.PP
Definition at line 472 of file gmock\-spec\-builders\&.cc\&.
.SS "FunctionMockers function_mockers"

.PP
Definition at line 475 of file gmock\-spec\-builders\&.cc\&.
.SS "bool leakable"

.PP
Definition at line 474 of file gmock\-spec\-builders\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
