.TH "build/_deps/googletest-src/googlemock/test/gmock_leak_test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock_leak_test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgmock_leak_test\&.GMockLeakTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgmock_leak_test\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgmock_leak_test\&.PROGRAM_PATH\fP = \fBgmock_test_utils\&.GetTestExecutablePath\fP('gmock_leak_test_')"
.br
.ti -1c
.RI "list \fBgmock_leak_test\&.TEST_WITH_EXPECT_CALL\fP = [PROGRAM_PATH, '\-\-gtest_filter=*ExpectCall*']"
.br
.ti -1c
.RI "list \fBgmock_leak_test\&.TEST_WITH_ON_CALL\fP = [PROGRAM_PATH, '\-\-gtest_filter=*OnCall*']"
.br
.ti -1c
.RI "list \fBgmock_leak_test\&.TEST_MULTIPLE_LEAKS\fP = [PROGRAM_PATH, '\-\-gtest_filter=*MultipleLeaked*']"
.br
.ti -1c
.RI "\fBgmock_leak_test\&.environ\fP = gmock_test_utils\&.environ"
.br
.ti -1c
.RI "\fBgmock_leak_test\&.SetEnvVar\fP = gmock_test_utils\&.SetEnvVar"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
