.TH "build/_deps/googletest-src/googlemock/include/gmock/gmock-more-matchers.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/include/gmock/gmock-more-matchers.h
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gmock/gmock\-matchers\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtesting::internal::IsEmptyMatcher\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "PolymorphicMatcher< internal::IsEmptyMatcher > \fBtesting::IsEmpty\fP ()"
.br
.ti -1c
.RI "\fBtesting::MATCHER\fP (IsTrue, negation ? 'is false' :'is true')"
.br
.ti -1c
.RI "\fBtesting::MATCHER\fP (IsFalse, negation ? 'is true' :'is false')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
