.TH "build/_deps/googletest-src/googlemock/include/gmock/gmock-cardinalities.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/include/gmock/gmock-cardinalities.h
.SH SYNOPSIS
.br
.PP
\fC#include <limits\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include 'gmock/internal/gmock\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_DISABLE_MSC_WARNINGS_PUSH_\fP (4251) namespace testing"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "GTEST_DISABLE_MSC_WARNINGS_PUSH_ (4251)"

.PP
Definition at line 50 of file gmock\-cardinalities\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
