.TH "build/_deps/googletest-src/googlemock/src/gmock-matchers.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/src/gmock-matchers.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gmock/gmock\-matchers\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtesting::internal::MaxBipartiteMatchState\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP std::string \fBtesting::internal::FormatMatcherDescription\fP (bool negation, const char *matcher_name, const std::vector< const char * > &param_names, const Strings &param_values)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP ElementMatcherPairs \fBtesting::internal::FindMaxBipartiteMatching\fP (const MatchMatrix &g)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
