.TH "build/_deps/googletest-src/googlemock/test/gmock_link2_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googlemock/test/gmock_link2_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'test/gmock_link_test\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLinkTest\fP   LinkTest2"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LinkTest   LinkTest2"

.PP
Definition at line 36 of file gmock_link2_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
