.TH "build/_deps/googletest-src/googletest/test/googletest-color-test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-color-test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-color\-test\&.GTestColorTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-color\-test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgoogletest\-color\-test\&.SetEnvVar\fP (env_var, \fBvalue\fP)"
.br
.ti -1c
.RI "def \fBgoogletest\-color\-test\&.UsesColor\fP (term, color_env_var, color_flag)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-color\-test\&.IS_WINDOWS\fP = 'nt'"
.br
.ti -1c
.RI "string \fBgoogletest\-color\-test\&.COLOR_ENV_VAR\fP = 'GTEST_COLOR'"
.br
.ti -1c
.RI "string \fBgoogletest\-color\-test\&.COLOR_FLAG\fP = 'gtest_color'"
.br
.ti -1c
.RI "\fBgoogletest\-color\-test\&.COMMAND\fP = \fBgtest_test_utils\&.GetTestExecutablePath\fP('googletest\-color\-test_')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
