.TH "build/_deps/googletest-src/googletest/test/googletest-json-output-unittest.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-json-output-unittest.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-json\-output\-unittest\&.GTestJsonOutputUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-json\-output\-unittest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.GTEST_FILTER_FLAG\fP = '\-\-gtest_filter'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.GTEST_LIST_TESTS_FLAG\fP = '\-\-gtest_list_tests'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.GTEST_OUTPUT_FLAG\fP = '\-\-gtest_output'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.GTEST_DEFAULT_OUTPUT_FILE\fP = 'test_detail\&.json'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.GTEST_PROGRAM_NAME\fP = 'gtest_xml_output_unittest_'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.NO_STACKTRACE_SUPPORT_FLAG\fP = '\-\-no_stacktrace_support'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.SUPPORTS_STACK_TRACES\fP = NO_STACKTRACE_SUPPORT_FLAG not in sys\&.argv"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-output\-unittest\&.STACK_TRACE_TEMPLATE\fP = '\\nStack trace:\\n*'"
.br
.ti -1c
.RI "dictionary \fBgoogletest\-json\-output\-unittest\&.EXPECTED_NON_EMPTY\fP"
.br
.ti -1c
.RI "dictionary \fBgoogletest\-json\-output\-unittest\&.EXPECTED_FILTERED\fP"
.br
.ti -1c
.RI "dictionary \fBgoogletest\-json\-output\-unittest\&.EXPECTED_NO_TEST\fP"
.br
.ti -1c
.RI "\fBgoogletest\-json\-output\-unittest\&.GTEST_PROGRAM_PATH\fP = \fBgtest_test_utils\&.GetTestExecutablePath\fP(GTEST_PROGRAM_NAME)"
.br
.ti -1c
.RI "tuple \fBgoogletest\-json\-output\-unittest\&.SUPPORTS_TYPED_TESTS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
