.TH "build/_deps/googletest-src/googletest/test/googletest-json-outfiles-test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-json-outfiles-test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-json\-outfiles\-test\&.GTestJsonOutFilesTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-json\-outfiles\-test\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-json\-outfiles\-test\&.GTEST_OUTPUT_SUBDIR\fP = 'json_outfiles'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-outfiles\-test\&.GTEST_OUTPUT_1_TEST\fP = 'gtest_xml_outfile1_test_'"
.br
.ti -1c
.RI "string \fBgoogletest\-json\-outfiles\-test\&.GTEST_OUTPUT_2_TEST\fP = 'gtest_xml_outfile2_test_'"
.br
.ti -1c
.RI "dictionary \fBgoogletest\-json\-outfiles\-test\&.EXPECTED_1\fP"
.br
.ti -1c
.RI "dictionary \fBgoogletest\-json\-outfiles\-test\&.EXPECTED_2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
