.TH "build/_deps/googletest-src/googletest/test/googletest-options-test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-options-test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'src/gtest\-internal\-inl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "FilePath original_working_dir_\fC [protected]\fP"

.PP
Definition at line 142 of file googletest\-options\-test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
