.TH "build/_deps/googletest-src/googletest/test/googletest-global-environment-unittest.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-global-environment-unittest.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-global\-environment\-unittest\&.GTestGlobalEnvironmentUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-global\-environment\-unittest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgoogletest\-global\-environment\-unittest\&.RunAndReturnOutput\fP (args=None)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
