.TH "build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <exception>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTerminateHandler\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 52 of file googletest\-throw\-on\-failure\-test_\&.cc\&.
.SS "void TerminateHandler ()"

.PP
Definition at line 46 of file googletest\-throw\-on\-failure\-test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
