.TH "build/_deps/googletest-src/googletest/test/googletest-filepath-test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-filepath-test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-filepath\&.h'\fP
.br
\fC#include 'src/gtest\-internal\-inl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "FilePath testdata_file_\fC [protected]\fP"

.PP
Definition at line 521 of file googletest\-filepath\-test\&.cc\&.
.SS "FilePath testdata_path_\fC [protected]\fP"

.PP
Definition at line 520 of file googletest\-filepath\-test\&.cc\&.
.SS "FilePath unique_file0_\fC [protected]\fP"

.PP
Definition at line 522 of file googletest\-filepath\-test\&.cc\&.
.SS "FilePath unique_file1_\fC [protected]\fP"

.PP
Definition at line 523 of file googletest\-filepath\-test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
