.TH "build/_deps/googletest-src/googletest/test/googletest-setuptestsuite-test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-setuptestsuite-test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSetupFailTest\fP"
.br
.ti -1c
.RI "class \fBTearDownFailTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBSetupFailTest\fP, NoopPassingTest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTearDownFailTest\fP, NoopPassingTest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBSetupFailTest\fP, NoopPassingTest)"

.PP
Definition at line 37 of file googletest\-setuptestsuite\-test_\&.cc\&.
.SS "TEST_F (\fBTearDownFailTest\fP, NoopPassingTest)"

.PP
Definition at line 44 of file googletest\-setuptestsuite\-test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
