.TH "build/_deps/googletest-src/googletest/test/googletest-param-test2-test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-param-test2-test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'test/googletest\-param\-test\-test\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBINSTANTIATE_TEST_SUITE_P\fP (MultiplesOf33, \fBExternalInstantiationTest\fP, Values(33, 66))"
.br
.ti -1c
.RI "\fBINSTANTIATE_TEST_SUITE_P\fP (Sequence2, \fBInstantiationInMultipleTranslationUnitsTest\fP, Values(42 *3, 42 *4, 42 *5))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ParamGenerator< int > \fBextern_gen\fP = Values(33)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "INSTANTIATE_TEST_SUITE_P (MultiplesOf33, \fBExternalInstantiationTest\fP, Values(33, 66))"

.SS "INSTANTIATE_TEST_SUITE_P (Sequence2, \fBInstantiationInMultipleTranslationUnitsTest\fP, Values(42 *3, 42 *4, 42 *5))"

.SH "Variable Documentation"
.PP 
.SS "ParamGenerator<int> extern_gen = Values(33)"

.PP
Definition at line 43 of file googletest\-param\-test2\-test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
