.TH "build/_deps/googletest-src/googletest/test/googletest-failfast-unittest.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-failfast-unittest.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-failfast\-unittest\&.GTestFailFastUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-failfast\-unittest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgoogletest\-failfast\-unittest\&.SetEnvVar\fP (env_var, \fBvalue\fP)"
.br
.ti -1c
.RI "def \fBgoogletest\-failfast\-unittest\&.RunAndReturnOutput\fP (test_suite=None, fail_fast=None, run_disabled=False)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.BAZEL_FAIL_FAST_ENV_VAR\fP = 'TESTBRIDGE_TEST_RUNNER_FAIL_FAST'"
.br
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.FAIL_FAST_ENV_VAR\fP = 'GTEST_FAIL_FAST'"
.br
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.FAIL_FAST_FLAG\fP = 'gtest_fail_fast'"
.br
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.RUN_DISABLED_FLAG\fP = 'gtest_also_run_disabled_tests'"
.br
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.FILTER_FLAG\fP = 'gtest_filter'"
.br
.ti -1c
.RI "\fBgoogletest\-failfast\-unittest\&.COMMAND\fP"
.br
.ti -1c
.RI "string \fBgoogletest\-failfast\-unittest\&.LIST_TESTS_FLAG\fP = '\-\-gtest_list_tests'"
.br
.ti -1c
.RI "tuple \fBgoogletest\-failfast\-unittest\&.SUPPORTS_DEATH_TESTS\fP"
.br
.ti -1c
.RI "\fBgoogletest\-failfast\-unittest\&.environ\fP = os\&.environ\&.copy()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
