.TH "build/_deps/googletest-src/googletest/test/googletest-env-var-test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-env-var-test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-env\-var\-test\&.GTestEnvVarTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-env\-var\-test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgoogletest\-env\-var\-test\&.AssertEq\fP (expected, actual)"
.br
.ti -1c
.RI "def \fBgoogletest\-env\-var\-test\&.SetEnvVar\fP (env_var, \fBvalue\fP)"
.br
.ti -1c
.RI "def \fBgoogletest\-env\-var\-test\&.GetFlag\fP (flag)"
.br
.ti -1c
.RI "def \fBgoogletest\-env\-var\-test\&.TestFlag\fP (flag, test_val, default_val)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-env\-var\-test\&.IS_WINDOWS\fP = 'nt'"
.br
.ti -1c
.RI "string \fBgoogletest\-env\-var\-test\&.IS_LINUX\fP = 'Linux'"
.br
.ti -1c
.RI "\fBgoogletest\-env\-var\-test\&.COMMAND\fP = \fBgtest_test_utils\&.GetTestExecutablePath\fP('googletest\-env\-var\-test_')"
.br
.ti -1c
.RI "\fBgoogletest\-env\-var\-test\&.environ\fP = os\&.environ\&.copy()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
