.TH "build/_deps/googletest-src/googletest/test/googletest-death-test-test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-death-test-test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\-death\-test\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-filepath\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
