.TH "build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgoogletest\-catch\-exceptions\-test\&.CatchSehExceptionsTest\fP"
.br
.ti -1c
.RI "class \fBgoogletest\-catch\-exceptions\-test\&.CatchCxxExceptionsTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoogletest\-catch\-exceptions\-test\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgoogletest\-catch\-exceptions\-test\&.FLAG_PREFIX\fP = '\-\-gtest_'"
.br
.ti -1c
.RI "string \fBgoogletest\-catch\-exceptions\-test\&.LIST_TESTS_FLAG\fP = FLAG_PREFIX + 'list_tests'"
.br
.ti -1c
.RI "string \fBgoogletest\-catch\-exceptions\-test\&.NO_CATCH_EXCEPTIONS_FLAG\fP = FLAG_PREFIX + 'catch_exceptions=0'"
.br
.ti -1c
.RI "string \fBgoogletest\-catch\-exceptions\-test\&.FILTER_FLAG\fP = FLAG_PREFIX + 'filter'"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.EX_EXE_PATH\fP"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.EXE_PATH\fP"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.environ\fP = gtest_test_utils\&.environ"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.SetEnvVar\fP = gtest_test_utils\&.SetEnvVar"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.TEST_LIST\fP"
.br
.ti -1c
.RI "string \fBgoogletest\-catch\-exceptions\-test\&.SUPPORTS_SEH_EXCEPTIONS\fP = 'ThrowsSehException' in TEST_LIST"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.BINARY_OUTPUT\fP = \fBgtest_test_utils\&.Subprocess\fP([EXE_PATH], env=environ)\&.output"
.br
.ti -1c
.RI "\fBgoogletest\-catch\-exceptions\-test\&.EX_BINARY_OUTPUT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
