.TH "Gradebook" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gradebook \- Class for a gradebook\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gradebook\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBget_GPA\fP ()"
.br
.RI "Method for taking grades of \fBGradebook\fP object and calculating GPA\&. "
.ti -1c
.RI "int \fBget_Name\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (int name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for a gradebook\&. 
.PP
Definition at line 12 of file gradebook\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double Gradebook::get_GPA ()"

.PP
Method for taking grades of \fBGradebook\fP object and calculating GPA\&. 
.PP
\fBReturns\fP
.RS 4
double 
.RE
.PP

.PP
Definition at line 31 of file gradebook\&.hpp\&.
.SS "int Gradebook::get_Name ()\fC [inline]\fP"

.PP
Definition at line 19 of file gradebook\&.hpp\&.
.SS "void Gradebook::setName (int name)\fC [inline]\fP"

.PP
Definition at line 20 of file gradebook\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
