.TH "Problem1-1/include/gradebook.hpp" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Problem1-1/include/gradebook.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGradebook\fP"
.br
.RI "Class for a gradebook\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
