.TH "build/_deps/googletest-src/googletest/test/gtest_xml_test_utils.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_xml_test_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_xml_test_utils\&.GTestXMLTestCase\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_xml_test_utils\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_xml_test_utils\&.GTEST_DEFAULT_OUTPUT_FILE\fP = 'test_detail\&.xml'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
