.TH "build/_deps/googletest-src/googletest/test/gtest_xml_outfiles_test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_xml_outfiles_test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_xml_outfiles_test\&.GTestXMLOutFilesTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_xml_outfiles_test\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_xml_outfiles_test\&.GTEST_OUTPUT_SUBDIR\fP = 'xml_outfiles'"
.br
.ti -1c
.RI "string \fBgtest_xml_outfiles_test\&.GTEST_OUTPUT_1_TEST\fP = 'gtest_xml_outfile1_test_'"
.br
.ti -1c
.RI "string \fBgtest_xml_outfiles_test\&.GTEST_OUTPUT_2_TEST\fP = 'gtest_xml_outfile2_test_'"
.br
.ti -1c
.RI "string \fBgtest_xml_outfiles_test\&.EXPECTED_XML_1\fP"
.br
.ti -1c
.RI "string \fBgtest_xml_outfiles_test\&.EXPECTED_XML_2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
