.TH "build/_deps/googletest-src/googletest/include/gtest/internal/gtest-filepath.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-filepath.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-string\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
