.TH "build/_deps/googletest-src/googletest/test/gtest_skip_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_skip_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFixture\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (SkipTest, DoesSkip)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBFixture\fP, SkipsOneTest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBFixture\fP, SkipsAnotherTest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (SkipTest, DoesSkip)"

.PP
Definition at line 37 of file gtest_skip_test\&.cc\&.
.SS "TEST_F (\fBFixture\fP, SkipsAnotherTest)"

.PP
Definition at line 51 of file gtest_skip_test\&.cc\&.
.SS "TEST_F (\fBFixture\fP, SkipsOneTest)"

.PP
Definition at line 49 of file gtest_skip_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
