.TH "build/_deps/googletest-src/googletest/test/gtest_prod_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_prod_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'production\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBtesting::Test\fP \fBPrivateCodeFixtureTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (PrivateCodeTest, CanAccessPrivateMembers)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBPrivateCodeFixtureTest\fP, CanAccessPrivateMembers)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBtesting::Test\fP \fBPrivateCodeFixtureTest\fP"

.PP
Definition at line 46 of file gtest_prod_test\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "TEST (PrivateCodeTest, CanAccessPrivateMembers)"

.PP
Definition at line 38 of file gtest_prod_test\&.cc\&.
.SS "TEST_F (\fBPrivateCodeFixtureTest\fP, CanAccessPrivateMembers)"

.PP
Definition at line 50 of file gtest_prod_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
