.TH "build/_deps/googletest-src/googletest/src/gtest_main.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/src/gtest_main.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBGTEST_API_\fP int main (int argc, char ** argv)"

.PP
Definition at line 61 of file gtest_main\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
