.TH "build/_deps/googletest-src/googletest/test/gtest_xml_outfile2_test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_xml_outfile2_test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include <atomic>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPropertyTwo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBPropertyTwo\fP, TestInt64ConvertibleProperties)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBPropertyTwo\fP, TestInt64ConvertibleProperties)"

.PP
Definition at line 43 of file gtest_xml_outfile2_test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
