.TH "build/_deps/googletest-src/googletest/test/gtest_xml_outfile1_test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_xml_outfile1_test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPropertyOne\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBPropertyOne\fP, TestSomeProperties)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBPropertyOne\fP, TestSomeProperties)"

.PP
Definition at line 41 of file gtest_xml_outfile1_test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
