.TH "build/_deps/googletest-src/googletest/test/gtest_throw_on_failure_ex_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_throw_on_failure_ex_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFail\fP (const char *msg)"
.br
.ti -1c
.RI "void \fBTestFailureThrowsRuntimeError\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Fail (const char * msg)"

.PP
Definition at line 44 of file gtest_throw_on_failure_ex_test\&.cc\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 79 of file gtest_throw_on_failure_ex_test\&.cc\&.
.SS "void TestFailureThrowsRuntimeError ()"

.PP
Definition at line 52 of file gtest_throw_on_failure_ex_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
