.TH "build/_deps/googletest-src/googletest/test/gtest_xml_output_unittest.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_xml_output_unittest.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_xml_output_unittest\&.GTestXMLOutputUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_xml_output_unittest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.GTEST_FILTER_FLAG\fP = '\-\-gtest_filter'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.GTEST_LIST_TESTS_FLAG\fP = '\-\-gtest_list_tests'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.GTEST_OUTPUT_FLAG\fP = '\-\-gtest_output'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.GTEST_DEFAULT_OUTPUT_FILE\fP = 'test_detail\&.xml'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.GTEST_PROGRAM_NAME\fP = 'gtest_xml_output_unittest_'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.NO_STACKTRACE_SUPPORT_FLAG\fP = '\-\-no_stacktrace_support'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.TOTAL_SHARDS_ENV_VAR\fP = 'GTEST_TOTAL_SHARDS'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.SHARD_INDEX_ENV_VAR\fP = 'GTEST_SHARD_INDEX'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.SHARD_STATUS_FILE_ENV_VAR\fP = 'GTEST_SHARD_STATUS_FILE'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.SUPPORTS_STACK_TRACES\fP = NO_STACKTRACE_SUPPORT_FLAG not in sys\&.argv"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.STACK_TRACE_TEMPLATE\fP = '\\nStack trace:\\n*'"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.STACK_TRACE_ENTITY_TEMPLATE\fP = ''"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.EXPECTED_NON_EMPTY_XML\fP"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.EXPECTED_FILTERED_TEST_XML\fP"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.EXPECTED_SHARDED_TEST_XML\fP"
.br
.ti -1c
.RI "string \fBgtest_xml_output_unittest\&.EXPECTED_NO_TEST_XML\fP"
.br
.ti -1c
.RI "\fBgtest_xml_output_unittest\&.GTEST_PROGRAM_PATH\fP = \fBgtest_test_utils\&.GetTestExecutablePath\fP(GTEST_PROGRAM_NAME)"
.br
.ti -1c
.RI "tuple \fBgtest_xml_output_unittest\&.SUPPORTS_TYPED_TESTS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
