.TH "build/_deps/googletest-src/googletest/test/gtest_testbridge_test_.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_testbridge_test_.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (TestFilterTest, TestThatSucceeds)"
.br
.ti -1c
.RI "\fBTEST\fP (TestFilterTest, TestThatFails)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (TestFilterTest, TestThatFails)"

.PP
Definition at line 40 of file gtest_testbridge_test_\&.cc\&.
.SS "TEST (TestFilterTest, TestThatSucceeds)"

.PP
Definition at line 38 of file gtest_testbridge_test_\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
