.TH "build/_deps/googletest-src/googletest/test/gtest_test_utils.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_test_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_test_utils\&.Subprocess\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_test_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgtest_test_utils\&.SetEnvVar\fP (env_var, \fBvalue\fP)"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetFlag\fP (flag)"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetSourceDir\fP ()"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetBuildDir\fP ()"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetTempDir\fP ()"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetTestExecutablePath\fP (executable_name, build_dir=None)"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.GetExitStatus\fP (exit_code)"
.br
.ti -1c
.RI "def \fBgtest_test_utils\&.Main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_test_utils\&.IS_WINDOWS\fP = 'nt'"
.br
.ti -1c
.RI "string \fBgtest_test_utils\&.IS_CYGWIN\fP = 'posix' and 'CYGWIN' in os\&.uname()[0]"
.br
.ti -1c
.RI "string \fBgtest_test_utils\&.IS_OS2\fP = 'os2'"
.br
.ti -1c
.RI "string \fBgtest_test_utils\&.GTEST_OUTPUT_VAR_NAME\fP = 'GTEST_OUTPUT'"
.br
.ti -1c
.RI "string \fBgtest_test_utils\&.PREMATURE_EXIT_FILE_ENV_VAR\fP = 'TEST_PREMATURE_EXIT_FILE'"
.br
.ti -1c
.RI "\fBgtest_test_utils\&.environ\fP = os\&.environ\&.copy()"
.br
.ti -1c
.RI "\fBgtest_test_utils\&.TestCase\fP = _test_module\&.TestCase"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
