.TH "build/_deps/googletest-src/googletest/src/gtest-filepath.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/src/gtest-filepath.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/internal/gtest\-filepath\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gtest/gtest\-message\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <climits>\fP
.br
\fC#include 'gtest/internal/gtest\-string\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGTEST_PATH_MAX_\fP   _POSIX_PATH_MAX"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GTEST_PATH_MAX_   _POSIX_PATH_MAX"

.PP
Definition at line 60 of file gtest\-filepath\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
