.TH "build/_deps/googletest-src/googletest/test/gtest_help_test.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_help_test.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_help_test\&.GTestHelpTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_help_test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgtest_help_test\&.RunWithFlag\fP (flag)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_help_test\&.IS_DARWIN\fP = 'Darwin'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.IS_LINUX\fP = 'Linux'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.IS_GNUHURD\fP = 'GNU'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.IS_GNUKFREEBSD\fP = 'GNU/kFreeBSD'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.IS_OPENBSD\fP = 'OpenBSD'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.IS_WINDOWS\fP = 'nt'"
.br
.ti -1c
.RI "\fBgtest_help_test\&.PROGRAM_PATH\fP = \fBgtest_test_utils\&.GetTestExecutablePath\fP('gtest_help_test_')"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.FLAG_PREFIX\fP = '\-\-gtest_'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.DEATH_TEST_STYLE_FLAG\fP = FLAG_PREFIX + 'death_test_style'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.STREAM_RESULT_TO_FLAG\fP = FLAG_PREFIX + 'stream_result_to'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.LIST_TESTS_FLAG\fP = FLAG_PREFIX + 'list_tests'"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.INTERNAL_FLAG_FOR_TESTING\fP = FLAG_PREFIX + 'internal_flag_for_testing'"
.br
.ti -1c
.RI "tuple \fBgtest_help_test\&.SUPPORTS_DEATH_TESTS\fP"
.br
.ti -1c
.RI "string \fBgtest_help_test\&.HAS_ABSL_FLAGS\fP = '\-\-has_absl_flags' in sys\&.argv"
.br
.ti -1c
.RI "\fBgtest_help_test\&.HELP_REGEX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
