.TH "build/_deps/googletest-src/googletest/include/gtest/internal/gtest-death-test-internal.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-death-test-internal.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gtest/gtest\-matchers\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-internal\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_DECLARE_string_\fP (internal_run_death_test)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBtesting::internal::kDeathTestStyleFlag\fP [] = 'death_test_style'"
.br
.ti -1c
.RI "const char \fBtesting::internal::kDeathTestUseFork\fP [] = 'death_test_use_fork'"
.br
.ti -1c
.RI "const char \fBtesting::internal::kInternalRunDeathTestFlag\fP [] = 'internal_run_death_test'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "GTEST_DECLARE_string_ (internal_run_death_test)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
