.TH "build/_deps/googletest-src/googletest/test/gtest_list_output_unittest.py" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_list_output_unittest.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgtest_list_output_unittest\&.GTestListTestsOutputUnitTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgtest_list_output_unittest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBgtest_list_output_unittest\&.GTEST_LIST_TESTS_FLAG\fP = '\-\-gtest_list_tests'"
.br
.ti -1c
.RI "string \fBgtest_list_output_unittest\&.GTEST_OUTPUT_FLAG\fP = '\-\-gtest_output'"
.br
.ti -1c
.RI "string \fBgtest_list_output_unittest\&.EXPECTED_XML\fP"
.br
.ti -1c
.RI "string \fBgtest_list_output_unittest\&.EXPECTED_JSON\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
