.TH "build/_deps/googletest-src/googletest/test/gtest-unittest-api_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest-unittest-api_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtesting::internal::LessByName< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::UnitTestHelper\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TestSuiteWithCommentTest< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::FinalSuccessChecker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtesting::internal::TYPED_TEST_SUITE\fP (TestSuiteWithCommentTest, Types< int >)"
.br
.ti -1c
.RI "\fBtesting::internal::TYPED_TEST\fP (TestSuiteWithCommentTest, Dummy)"
.br
.ti -1c
.RI "\fBtesting::internal::TEST\fP (ApiTest, UnitTestImmutableAccessorsWork)"
.br
.ti -1c
.RI "AssertionResult \fBtesting::internal::IsNull\fP (const char *str)"
.br
.ti -1c
.RI "\fBtesting::internal::TEST\fP (ApiTest, TestSuiteImmutableAccessorsWork)"
.br
.ti -1c
.RI "\fBtesting::internal::TEST\fP (ApiTest, TestSuiteDisabledAccessorsWork)"
.br
.ti -1c
.RI "\fBtesting::internal::TEST\fP (ApiTest, DISABLED_Dummy1)"
.br
.ti -1c
.RI "\fBtesting::internal::TEST\fP (DISABLED_Test, Dummy2)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBtesting::internal::kTypedTestSuites\fP = 1"
.br
.ti -1c
.RI "const int \fBtesting::internal::kTypedTests\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 322 of file gtest\-unittest\-api_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
