.TH "build/_deps/googletest-src/googletest/src/gtest-port.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/src/gtest-port.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'gtest/gtest\-message\&.h'\fP
.br
\fC#include 'gtest/gtest\-spi\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-internal\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-string\&.h'\fP
.br
\fC#include 'src/gtest\-internal\-inl\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP size_t \fBtesting::internal::GetThreadCount\fP ()"
.br
.ti -1c
.RI "\fBGTEST_API_\fP ::std::string \fBtesting::internal::FormatFileLocation\fP (const char *file, int line)"
.br
.ti -1c
.RI "\fBGTEST_DISABLE_MSC_WARNINGS_POP_\fP() \fBGTEST_API_\fP \fBGTEST_API_\fP ::std::string \fBtesting::internal::FormatCompilerIndependentFileLocation\fP (const char *file, int line)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP size_t \fBtesting::internal::GetFileSize\fP (FILE *file)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP std::string \fBtesting::internal::ReadEntireFile\fP (FILE *file)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP bool \fBtesting::internal::ParseInt32\fP (const Message &src_text, const char *str, int32_t *\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBtesting::internal::BoolFromGTestEnv\fP (const char *flag, bool default_val)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP int32_t \fBtesting::internal::Int32FromGTestEnv\fP (const char *flag, int32_t default_val)"
.br
.ti -1c
.RI "std::string \fBtesting::internal::OutputFlagAlsoCheckEnvVar\fP ()"
.br
.ti -1c
.RI "const char * \fBtesting::internal::StringFromGTestEnv\fP (const char *flag, const char *default_val)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBtesting::internal::kUnknownFile\fP [] = 'unknown file'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
