.TH "build/_deps/googletest-src/googletest/test/gtest_assert_by_exception_test.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/test/gtest_assert_by_exception_test.cc
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThrowListener\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFail\fP (const char *msg)"
.br
.ti -1c
.RI "\fBTEST\fP (Test, Test)"
.br
.ti -1c
.RI "\fBTEST\fP (Test, Test2)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBkTestForContinuingTest\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Fail (const char * msg)"

.PP
Definition at line 52 of file gtest_assert_by_exception_test\&.cc\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 98 of file gtest_assert_by_exception_test\&.cc\&.
.SS "TEST (Test, Test)"

.PP
Definition at line 62 of file gtest_assert_by_exception_test\&.cc\&.
.SS "TEST (Test, Test2)"

.PP
Definition at line 96 of file gtest_assert_by_exception_test\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "int kTestForContinuingTest = 0"

.PP
Definition at line 94 of file gtest_assert_by_exception_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
