.TH "build/_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <set>\fP
.br
\fC#include <string>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gtest/gtest\-printers\&.h'\fP
.br
\fC#include 'gtest/gtest\-test\-part\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-internal\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtesting::TestParamInfo< ParamType >\fP"
.br
.ti -1c
.RI "struct \fBtesting::PrintToStringParamName\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamIteratorInterface< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamIterator< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamGeneratorInterface< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamGenerator< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::RangeGenerator< T, IncrementT >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestFactory< TestClass >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TestMetaFactoryBase< ParamType >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TestMetaFactory< TestSuite >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestSuiteInfoBase\fP"
.br
.ti -1c
.RI "struct \fBtesting::internal::MarkAsIgnored\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestSuiteInfo< TestSuite >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestSuiteRegistry\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TypeParameterizedTestSuiteRegistry\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ValueArray< Ts >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::CartesianProductHolder< Gen >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamGeneratorConverter< From, To >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamConverterGenerator< Gen >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtesting\fP"
.br
.ti -1c
.RI " \fBtesting::internal\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "template<class TestCase > using \fBtesting::internal::ParameterizedTestCaseInfo\fP = ParameterizedTestSuiteInfo< TestCase >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::ReportInvalidTestSuiteType\fP (const char *test_suite_name, CodeLocation code_location)"
.br
.ti -1c
.RI "template<class ParamType > std::string \fBtesting::internal::DefaultParamName\fP (const TestParamInfo< ParamType > &info)"
.br
.ti -1c
.RI "template<typename T  = int> void \fBtesting::internal::TestNotEmpty\fP ()"
.br
.ti -1c
.RI "template<typename T  = int> void \fBtesting::internal::TestNotEmpty\fP (const T &)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::InsertSyntheticTestCase\fP (const std::string &name, CodeLocation location, bool has_test_p)"
.br
.ti -1c
.RI "template<class Container > internal::ParamGenerator< typename Container::value_type > \fBtesting::ValuesIn\fP (const Container &container)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
