.TH "HasDebugStringMethods" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HasDebugStringMethods
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBInheritsDebugStringMethods\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBDebugString\fP () const"
.br
.ti -1c
.RI "std::string \fBShortDebugString\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7182 of file gtest_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string HasDebugStringMethods::DebugString () const\fC [inline]\fP"

.PP
Definition at line 7183 of file gtest_unittest\&.cc\&.
.SS "std::string HasDebugStringMethods::ShortDebugString () const\fC [inline]\fP"

.PP
Definition at line 7184 of file gtest_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
