.TH "IntWrapper" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntWrapper\fP (int a_value)"
.br
.ti -1c
.RI "\fBIntWrapper\fP (const \fBIntWrapper\fP &other)"
.br
.ti -1c
.RI "\fBIntWrapper\fP \fBoperator=\fP (const \fBIntWrapper\fP &other)"
.br
.ti -1c
.RI "\fBIntWrapper\fP \fBoperator+\fP (int other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBIntWrapper\fP &other) const"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 248 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntWrapper::IntWrapper (int a_value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 250 of file googletest\-param\-test\-test\&.cc\&.
.SS "IntWrapper::IntWrapper (const \fBIntWrapper\fP & other)\fC [inline]\fP"

.PP
Definition at line 251 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIntWrapper\fP IntWrapper::operator+ (int other) const\fC [inline]\fP"

.PP
Definition at line 258 of file googletest\-param\-test\-test\&.cc\&.
.SS "bool IntWrapper::operator< (const \fBIntWrapper\fP & other) const\fC [inline]\fP"

.PP
Definition at line 259 of file googletest\-param\-test\-test\&.cc\&.
.SS "\fBIntWrapper\fP IntWrapper::operator= (const \fBIntWrapper\fP & other)\fC [inline]\fP"

.PP
Definition at line 253 of file googletest\-param\-test\-test\&.cc\&.
.SS "int IntWrapper::value () const\fC [inline]\fP"

.PP
Definition at line 262 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
