.TH "InvokeHelper" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvokeHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmock_link_test\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVoidFromVoid\fP ()"
.br
.ti -1c
.RI "void \fBVoidFromString\fP (char *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBStaticVoidFromVoid\fP ()"
.br
.ti -1c
.RI "static void \fBStaticVoidFromString\fP (char *)"
.br
.ti -1c
.RI "static int \fBStaticIntFromString\fP (char *)"
.br
.ti -1c
.RI "static bool \fBStaticBoolFromString\fP (const char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 228 of file gmock_link_test\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool InvokeHelper::StaticBoolFromString (const char *)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 235 of file gmock_link_test\&.h\&.
.SS "static int InvokeHelper::StaticIntFromString (char *)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 234 of file gmock_link_test\&.h\&.
.SS "static void InvokeHelper::StaticVoidFromString (char *)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 232 of file gmock_link_test\&.h\&.
.SS "static void InvokeHelper::StaticVoidFromVoid ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 230 of file gmock_link_test\&.h\&.
.SS "void InvokeHelper::VoidFromString (char *)\fC [inline]\fP"

.PP
Definition at line 233 of file gmock_link_test\&.h\&.
.SS "void InvokeHelper::VoidFromVoid ()\fC [inline]\fP"

.PP
Definition at line 231 of file gmock_link_test\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
