.TH "include/lib.hpp" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/lib.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdummy\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dummy ()"

.PP
Definition at line 5 of file lib\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
