.TH "libs/lib1/lib1.hpp" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/lib1/lib1.hpp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_function1\fP (int input)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_function1 (int input)"

.PP
Definition at line 1 of file src\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
