.TH "libs/lib2/lib2.hpp" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libs/lib2/lib2.hpp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmy_function2\fP (double input)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double my_function2 (double input)"

.PP
Definition at line 1 of file src\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
