.TH "test/main.cpp" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'lib\&.hpp'\fP
.br
\fC#include 'lib1\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfunction_not_used\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void function_not_used ()"

.PP
Definition at line 6 of file main\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 11 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
