.TH "md_build__deps_googletest_src_docs_platforms" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_build__deps_googletest_src_docs_platforms \- Supported Platforms 
GoogleTest follows Google's \fCFoundational C++ Support Policy\fP\&. See \fCthis table\fP for a list of currently supported versions compilers, platforms, and build tools\&. 
