.TH "md_build__deps_googletest_src_docs_index" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_build__deps_googletest_src_docs_index \- GoogleTest User's Guide 

.SH "Welcome to GoogleTest!"
.PP
GoogleTest is Google's C++ testing and mocking framework\&. This user's guide has the following contents:
.PP
.IP "\(bu" 2
\fBGoogleTest Primer\fP - Teaches you how to write simple tests using GoogleTest\&. Read this first if you are new to GoogleTest\&.
.IP "\(bu" 2
\fBGoogleTest Advanced\fP - Read this when you've finished the Primer and want to utilize GoogleTest to its full potential\&.
.IP "\(bu" 2
\fBGoogleTest Samples\fP - Describes some GoogleTest samples\&.
.IP "\(bu" 2
\fBGoogleTest FAQ\fP - Have a question? Want some tips? Check here first\&.
.IP "\(bu" 2
\fBMocking for Dummies\fP - Teaches you how to create mock objects and use them in tests\&.
.IP "\(bu" 2
\fBMocking Cookbook\fP - Includes tips and approaches to common mocking use cases\&.
.IP "\(bu" 2
\fBMocking Cheat Sheet\fP - A handy reference for matchers, actions, invariants, and more\&.
.IP "\(bu" 2
\fBMocking FAQ\fP - Contains answers to some mocking-specific questions\&. 
.PP

