.TH "md_build__deps_googletest_src_docs_gmock_for_dummies" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_build__deps_googletest_src_docs_gmock_for_dummies \- gMock for Dummies 

.SH "What Is gMock?"
.PP
When you write a prototype or test, often it's not feasible or wise to rely on real objects entirely\&. A \fBmock object\fP implements the same interface as a real object (so it can be used as one), but lets you specify at run time how it will be used and what it should do (which methods will be called? in which order? how many times? with what arguments? what will they return? etc)\&.
.PP
It is easy to confuse the term \fIfake objects\fP with mock objects\&. Fakes and mocks actually mean very different things in the Test-Driven Development (TDD) community:
.PP
.IP "\(bu" 2
\fBFake\fP objects have working implementations, but usually take some shortcut (perhaps to make the operations less expensive), which makes them not suitable for production\&. An in-memory file system would be an example of a fake\&.
.IP "\(bu" 2
\fBMocks\fP are objects pre-programmed with \fIexpectations\fP, which form a specification of the calls they are expected to receive\&.
.PP
.PP
If all this seems too abstract for you, don't worry - the most important thing to remember is that a mock allows you to check the \fIinteraction\fP between itself and code that uses it\&. The difference between fakes and mocks shall become much clearer once you start to use mocks\&.
.PP
\fBgMock\fP is a library (sometimes we also call it a 'framework' to make it sound cool) for creating mock classes and using them\&. It does to C++ what jMock/EasyMock does to Java (well, more or less)\&.
.PP
When using gMock,
.PP
.IP "1." 4
first, you use some simple macros to describe the interface you want to mock, and they will expand to the implementation of your mock class;
.IP "2." 4
next, you create some mock objects and specify its expectations and behavior using an intuitive syntax;
.IP "3." 4
then you exercise code that uses the mock objects\&. gMock will catch any violation to the expectations as soon as it arises\&.
.PP
.SH "Why gMock?"
.PP
While mock objects help you remove unnecessary dependencies in tests and make them fast and reliable, using mocks manually in C++ is \fIhard\fP:
.PP
.IP "\(bu" 2
Someone has to implement the mocks\&. The job is usually tedious and error-prone\&. No wonder people go great distance to avoid it\&.
.IP "\(bu" 2
The quality of those manually written mocks is a bit, uh, unpredictable\&. You may see some really polished ones, but you may also see some that were hacked up in a hurry and have all sorts of ad hoc restrictions\&.
.IP "\(bu" 2
The knowledge you gained from using one mock doesn't transfer to the next one\&.
.PP
.PP
In contrast, Java and Python programmers have some fine mock frameworks (jMock, EasyMock, etc), which automate the creation of mocks\&. As a result, mocking is a proven effective technique and widely adopted practice in those communities\&. Having the right tool absolutely makes the difference\&.
.PP
gMock was built to help C++ programmers\&. It was inspired by jMock and EasyMock, but designed with C++'s specifics in mind\&. It is your friend if any of the following problems is bothering you:
.PP
.IP "\(bu" 2
You are stuck with a sub-optimal design and wish you had done more prototyping before it was too late, but prototyping in C++ is by no means 'rapid'\&.
.IP "\(bu" 2
Your tests are slow as they depend on too many libraries or use expensive resources (e\&.g\&. a database)\&.
.IP "\(bu" 2
Your tests are brittle as some resources they use are unreliable (e\&.g\&. the network)\&.
.IP "\(bu" 2
You want to test how your code handles a failure (e\&.g\&. a file checksum error), but it's not easy to cause one\&.
.IP "\(bu" 2
You need to make sure that your module interacts with other modules in the right way, but it's hard to observe the interaction; therefore you resort to observing the side effects at the end of the action, but it's awkward at best\&.
.IP "\(bu" 2
You want to 'mock out' your dependencies, except that they don't have mock implementations yet; and, frankly, you aren't thrilled by some of those hand-written mocks\&.
.PP
.PP
We encourage you to use gMock as
.PP
.IP "\(bu" 2
a \fIdesign\fP tool, for it lets you experiment with your interface design early and often\&. More iterations lead to better designs!
.IP "\(bu" 2
a \fItesting\fP tool to cut your tests' outbound dependencies and probe the interaction between your module and its collaborators\&.
.PP
.SH "Getting Started"
.PP
gMock is bundled with googletest\&.
.SH "A Case for Mock Turtles"
.PP
Let's look at an example\&. Suppose you are developing a graphics program that relies on a \fCLOGO\fP-like API for drawing\&. How would you test that it does the right thing? Well, you can run it and compare the screen with a golden screen snapshot, but let's admit it: tests like this are expensive to run and fragile (What if you just upgraded to a shiny new graphics card that has better anti-aliasing? Suddenly you have to update all your golden images\&.)\&. It would be too painful if all your tests are like this\&. Fortunately, you learned about \fCDependency Injection\fP and know the right thing to do: instead of having your application talk to the system API directly, wrap the API in an interface (say, \fCTurtle\fP) and code to that interface:
.PP
.PP
.nf
class Turtle {
  \&.\&.\&.
  virtual ~Turtle() {}
  virtual void PenUp() = 0;
  virtual void PenDown() = 0;
  virtual void Forward(int distance) = 0;
  virtual void Turn(int degrees) = 0;
  virtual void GoTo(int x, int y) = 0;
  virtual int GetX() const = 0;
  virtual int GetY() const = 0;
};
.fi
.PP
.PP
(Note that the destructor of \fCTurtle\fP \fBmust\fP be virtual, as is the case for \fBall\fP classes you intend to inherit from - otherwise the destructor of the derived class will not be called when you delete an object through a base pointer, and you'll get corrupted program states like memory leaks\&.)
.PP
You can control whether the turtle's movement will leave a trace using \fCPenUp()\fP and \fCPenDown()\fP, and control its movement using \fCForward()\fP, \fCTurn()\fP, and \fCGoTo()\fP\&. Finally, \fCGetX()\fP and \fCGetY()\fP tell you the current position of the turtle\&.
.PP
Your program will normally use a real implementation of this interface\&. In tests, you can use a mock implementation instead\&. This allows you to easily check what drawing primitives your program is calling, with what arguments, and in which order\&. Tests written this way are much more robust (they won't break because your new machine does anti-aliasing differently), easier to read and maintain (the intent of a test is expressed in the code, not in some binary images), and run \fImuch, much faster\fP\&.
.SH "Writing the Mock Class"
.PP
If you are lucky, the mocks you need to use have already been implemented by some nice people\&. If, however, you find yourself in the position to write a mock class, relax - gMock turns this task into a fun game! (Well, almost\&.)
.SS "How to Define It"
Using the \fCTurtle\fP interface as example, here are the simple steps you need to follow:
.PP
.IP "\(bu" 2
Derive a class \fCMockTurtle\fP from \fCTurtle\fP\&.
.IP "\(bu" 2
Take a \fIvirtual\fP function of \fCTurtle\fP (while it's possible to \fCmock non-virtual methods using templates\fP, it's much more involved)\&.
.IP "\(bu" 2
In the \fCpublic:\fP section of the child class, write \fC\fBMOCK_METHOD()\fP;\fP
.IP "\(bu" 2
Now comes the fun part: you take the function signature, cut-and-paste it into the macro, and add two commas - one between the return type and the name, another between the name and the argument list\&.
.IP "\(bu" 2
If you're mocking a const method, add a 4th parameter containing \fC(const)\fP (the parentheses are required)\&.
.IP "\(bu" 2
Since you're overriding a virtual method, we suggest adding the \fCoverride\fP keyword\&. For const methods the 4th parameter becomes \fC(const, override)\fP, for non-const methods just \fC(override)\fP\&. This isn't mandatory\&.
.IP "\(bu" 2
Repeat until all virtual functions you want to mock are done\&. (It goes without saying that \fIall\fP pure virtual methods in your abstract class must be either mocked or overridden\&.)
.PP
.PP
After the process, you should have something like:
.PP
.PP
.nf
#include <gmock/gmock\&.h>  // Brings in gMock\&.

class MockTurtle : public Turtle {
 public:
  \&.\&.\&.
  MOCK_METHOD(void, PenUp, (), (override));
  MOCK_METHOD(void, PenDown, (), (override));
  MOCK_METHOD(void, Forward, (int distance), (override));
  MOCK_METHOD(void, Turn, (int degrees), (override));
  MOCK_METHOD(void, GoTo, (int x, int y), (override));
  MOCK_METHOD(int, GetX, (), (const, override));
  MOCK_METHOD(int, GetY, (), (const, override));
};
.fi
.PP
.PP
You don't need to define these mock methods somewhere else - the \fCMOCK_METHOD\fP macro will generate the definitions for you\&. It's that simple!
.SS "Where to Put It"
When you define a mock class, you need to decide where to put its definition\&. Some people put it in a \fC_test\&.cc\fP\&. This is fine when the interface being mocked (say, \fCFoo\fP) is owned by the same person or team\&. Otherwise, when the owner of \fCFoo\fP changes it, your test could break\&. (You can't really expect \fCFoo\fP's maintainer to fix every test that uses \fCFoo\fP, can you?)
.PP
Generally, you should not mock classes you don't own\&. If you must mock such a class owned by others, define the mock class in \fCFoo\fP's Bazel package (usually the same directory or a \fCtesting\fP sub-directory), and put it in a \fC\&.h\fP and a \fCcc_library\fP with \fCtestonly=True\fP\&. Then everyone can reference them from their tests\&. If \fCFoo\fP ever changes, there is only one copy of \fC\fBMockFoo\fP\fP to change, and only tests that depend on the changed methods need to be fixed\&.
.PP
Another way to do it: you can introduce a thin layer \fCFooAdaptor\fP on top of \fCFoo\fP and code to this new interface\&. Since you own \fCFooAdaptor\fP, you can absorb changes in \fCFoo\fP much more easily\&. While this is more work initially, carefully choosing the adaptor interface can make your code easier to write and more readable (a net win in the long run), as you can choose \fCFooAdaptor\fP to fit your specific domain much better than \fCFoo\fP does\&.
.SH "Using Mocks in Tests"
.PP
Once you have a mock class, using it is easy\&. The typical work flow is:
.PP
.IP "1." 4
Import the gMock names from the \fCtesting\fP namespace such that you can use them unqualified (You only have to do it once per file)\&. Remember that namespaces are a good idea\&.
.IP "2." 4
Create some mock objects\&.
.IP "3." 4
Specify your expectations on them (How many times will a method be called? With what arguments? What should it do? etc\&.)\&.
.IP "4." 4
Exercise some code that uses the mocks; optionally, check the result using googletest assertions\&. If a mock method is called more than expected or with wrong arguments, you'll get an error immediately\&.
.IP "5." 4
When a mock is destructed, gMock will automatically check whether all expectations on it have been satisfied\&.
.PP
.PP
Here's an example:
.PP
.PP
.nf
#include "path/to/mock-turtle\&.h"
#include <gmock/gmock\&.h>
#include <gtest/gtest\&.h>

using ::testing::AtLeast;                         // #1

TEST(PainterTest, CanDrawSomething) {
  MockTurtle turtle;                              // #2
  EXPECT_CALL(turtle, PenDown())                  // #3
      \&.Times(AtLeast(1));

  Painter painter(&turtle);                       // #4

  EXPECT_TRUE(painter\&.DrawCircle(0, 0, 10));      // #5
}
.fi
.PP
.PP
As you might have guessed, this test checks that \fCPenDown()\fP is called at least once\&. If the \fCpainter\fP object didn't call this method, your test will fail with a message like this:
.PP
.PP
.nf
path/to/my_test\&.cc:119: Failure
Actual function call count doesn't match this expectation:
Actually: never called;
Expected: called at least once\&.
Stack trace:
\&.\&.\&.
.fi
.PP
.PP
\fBTip 1:\fP If you run the test from an Emacs buffer, you can hit \fC<Enter>\fP on the line number to jump right to the failed expectation\&.
.PP
\fBTip 2:\fP If your mock objects are never deleted, the final verification won't happen\&. Therefore it's a good idea to turn on the heap checker in your tests when you allocate mocks on the heap\&. You get that automatically if you use the \fCgtest_main\fP library already\&.
.PP
\fBImportant note:\fP gMock requires expectations to be set \fBbefore\fP the mock functions are called, otherwise the behavior is \fBundefined\fP\&. Do not alternate between calls to \fC\fBEXPECT_CALL()\fP\fP and calls to the mock functions, and do not set any expectations on a mock after passing the mock to an API\&.
.PP
This means \fC\fBEXPECT_CALL()\fP\fP should be read as expecting that a call will occur \fIin the future\fP, not that a call has occurred\&. Why does gMock work like that? Well, specifying the expectation beforehand allows gMock to report a violation as soon as it rises, when the context (stack trace, etc) is still available\&. This makes debugging much easier\&.
.PP
Admittedly, this test is contrived and doesn't do much\&. You can easily achieve the same effect without using gMock\&. However, as we shall reveal soon, gMock allows you to do \fIso much more\fP with the mocks\&.
.SH "Setting Expectations"
.PP
The key to using a mock object successfully is to set the \fIright expectations\fP on it\&. If you set the expectations too strict, your test will fail as the result of unrelated changes\&. If you set them too loose, bugs can slip through\&. You want to do it just right such that your test can catch exactly the kind of bugs you intend it to catch\&. gMock provides the necessary means for you to do it 'just
right\&.'
.SS "General Syntax"
In gMock we use the \fC\fBEXPECT_CALL()\fP\fP macro to set an expectation on a mock method\&. The general syntax is:
.PP
.PP
.nf
EXPECT_CALL(mock_object, method(matchers))
    \&.Times(cardinality)
    \&.WillOnce(action)
    \&.WillRepeatedly(action);
.fi
.PP
.PP
The macro has two arguments: first the mock object, and then the method and its arguments\&. Note that the two are separated by a comma (\fC,\fP), not a period (\fC\&.\fP)\&. (Why using a comma? The answer is that it was necessary for technical reasons\&.) If the method is not overloaded, the macro can also be called without matchers:
.PP
.PP
.nf
EXPECT_CALL(mock_object, non-overloaded-method)
    \&.Times(cardinality)
    \&.WillOnce(action)
    \&.WillRepeatedly(action);
.fi
.PP
.PP
This syntax allows the test writer to specify 'called with any arguments' without explicitly specifying the number or types of arguments\&. To avoid unintended ambiguity, this syntax may only be used for methods that are not overloaded\&.
.PP
Either form of the macro can be followed by some optional \fIclauses\fP that provide more information about the expectation\&. We'll discuss how each clause works in the coming sections\&.
.PP
This syntax is designed to make an expectation read like English\&. For example, you can probably guess that
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
EXPECT_CALL(turtle, GetX())
    \&.Times(5)
    \&.WillOnce(Return(100))
    \&.WillOnce(Return(150))
    \&.WillRepeatedly(Return(200));
.fi
.PP
.PP
says that the \fCturtle\fP object's \fCGetX()\fP method will be called five times, it will return 100 the first time, 150 the second time, and then 200 every time\&. Some people like to call this style of syntax a Domain-Specific Language (DSL)\&.
.PP
{: \&.callout \&.note} \fBNote:\fP Why do we use a macro to do this? Well it serves two purposes: first it makes expectations easily identifiable (either by \fCgrep\fP or by a human reader), and second it allows gMock to include the source file location of a failed expectation in messages, making debugging easier\&.
.SS "Matchers: What Arguments Do We Expect?"
When a mock function takes arguments, we may specify what arguments we are expecting, for example:
.PP
.PP
.nf
// Expects the turtle to move forward by 100 units\&.
EXPECT_CALL(turtle, Forward(100));
.fi
.PP
.PP
Oftentimes you do not want to be too specific\&. Remember that talk about tests being too rigid? Over specification leads to brittle tests and obscures the intent of tests\&. Therefore we encourage you to specify only what's necessary—no more, no less\&. If you aren't interested in the value of an argument, write \fC_\fP as the argument, which means 'anything goes':
.PP
.PP
.nf
using ::testing::_;
\&.\&.\&.
// Expects that the turtle jumps to somewhere on the x=50 line\&.
EXPECT_CALL(turtle, GoTo(50, _));
.fi
.PP
.PP
\fC_\fP is an instance of what we call \fBmatchers\fP\&. A matcher is like a predicate and can test whether an argument is what we'd expect\&. You can use a matcher inside \fC\fBEXPECT_CALL()\fP\fP wherever a function argument is expected\&. \fC_\fP is a convenient way of saying 'any value'\&.
.PP
In the above examples, \fC100\fP and \fC50\fP are also matchers; implicitly, they are the same as \fCEq(100)\fP and \fCEq(50)\fP, which specify that the argument must be equal (using \fCoperator==\fP) to the matcher argument\&. There are many \fBbuilt-in matchers\fP for common types (as well as \fCcustom matchers\fP); for example:
.PP
.PP
.nf
using ::testing::Ge;
\&.\&.\&.
// Expects the turtle moves forward by at least 100\&.
EXPECT_CALL(turtle, Forward(Ge(100)));
.fi
.PP
.PP
If you don't care about \fIany\fP arguments, rather than specify \fC_\fP for each of them you may instead omit the parameter list:
.PP
.PP
.nf
// Expects the turtle to move forward\&.
EXPECT_CALL(turtle, Forward);
// Expects the turtle to jump somewhere\&.
EXPECT_CALL(turtle, GoTo);
.fi
.PP
.PP
This works for all non-overloaded methods; if a method is overloaded, you need to help gMock resolve which overload is expected by specifying the number of arguments and possibly also the \fCtypes of the arguments\fP\&.
.SS "Cardinalities: How Many Times Will It Be Called?"
The first clause we can specify following an \fC\fBEXPECT_CALL()\fP\fP is \fCTimes()\fP\&. We call its argument a \fBcardinality\fP as it tells \fIhow many times\fP the call should occur\&. It allows us to repeat an expectation many times without actually writing it as many times\&. More importantly, a cardinality can be 'fuzzy', just like a matcher can be\&. This allows a user to express the intent of a test exactly\&.
.PP
An interesting special case is when we say \fCTimes(0)\fP\&. You may have guessed - it means that the function shouldn't be called with the given arguments at all, and gMock will report a googletest failure whenever the function is (wrongfully) called\&.
.PP
We've seen \fCAtLeast(n)\fP as an example of fuzzy cardinalities earlier\&. For the list of built-in cardinalities you can use, see \fChere\fP\&.
.PP
The \fCTimes()\fP clause can be omitted\&. \fBIf you omit \fCTimes()\fP, gMock will infer the cardinality for you\&.\fP The rules are easy to remember:
.PP
.IP "\(bu" 2
If \fBneither\fP \fC\fBWillOnce()\fP\fP \fBnor\fP \fCWillRepeatedly()\fP is in the \fC\fBEXPECT_CALL()\fP\fP, the inferred cardinality is \fCTimes(1)\fP\&.
.IP "\(bu" 2
If there are \fIn\fP \fC\fBWillOnce()\fP\fP's but \fBno\fP \fCWillRepeatedly()\fP, where \fIn\fP >= 1, the cardinality is \fCTimes(n)\fP\&.
.IP "\(bu" 2
If there are \fIn\fP \fC\fBWillOnce()\fP\fP's and \fBone\fP \fCWillRepeatedly()\fP, where \fIn\fP >= 0, the cardinality is \fCTimes(AtLeast(n))\fP\&.
.PP
.PP
\fBQuick quiz:\fP what do you think will happen if a function is expected to be called twice but actually called four times?
.SS "Actions: What Should It Do?"
Remember that a mock object doesn't really have a working implementation? We as users have to tell it what to do when a method is invoked\&. This is easy in gMock\&.
.PP
First, if the return type of a mock function is a built-in type or a pointer, the function has a \fBdefault action\fP (a \fCvoid\fP function will just return, a \fCbool\fP function will return \fCfalse\fP, and other functions will return 0)\&. In addition, in C++ 11 and above, a mock function whose return type is default-constructible (i\&.e\&. has a default constructor) has a default action of returning a default-constructed value\&. If you don't say anything, this behavior will be used\&.
.PP
Second, if a mock function doesn't have a default action, or the default action doesn't suit you, you can specify the action to be taken each time the expectation matches using a series of \fC\fBWillOnce()\fP\fP clauses followed by an optional \fCWillRepeatedly()\fP\&. For example,
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
EXPECT_CALL(turtle, GetX())
     \&.WillOnce(Return(100))
     \&.WillOnce(Return(200))
     \&.WillOnce(Return(300));
.fi
.PP
.PP
says that \fCturtle\&.GetX()\fP will be called \fIexactly three times\fP (gMock inferred this from how many \fC\fBWillOnce()\fP\fP clauses we've written, since we didn't explicitly write \fCTimes()\fP), and will return 100, 200, and 300 respectively\&.
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
EXPECT_CALL(turtle, GetY())
     \&.WillOnce(Return(100))
     \&.WillOnce(Return(200))
     \&.WillRepeatedly(Return(300));
.fi
.PP
.PP
says that \fCturtle\&.GetY()\fP will be called \fIat least twice\fP (gMock knows this as we've written two \fC\fBWillOnce()\fP\fP clauses and a \fCWillRepeatedly()\fP while having no explicit \fCTimes()\fP), will return 100 and 200 respectively the first two times, and 300 from the third time on\&.
.PP
Of course, if you explicitly write a \fCTimes()\fP, gMock will not try to infer the cardinality itself\&. What if the number you specified is larger than there are \fC\fBWillOnce()\fP\fP clauses? Well, after all \fC\fBWillOnce()\fP\fPs are used up, gMock will do the \fIdefault\fP action for the function every time (unless, of course, you have a \fCWillRepeatedly()\fP\&.)\&.
.PP
What can we do inside \fC\fBWillOnce()\fP\fP besides \fC\fBReturn()\fP\fP? You can return a reference using \fCReturnRef(\fP*\fCvariable\fP*\fC)\fP, or invoke a pre-defined function, among \fCothers\fP\&.
.PP
\fBImportant note:\fP The \fC\fBEXPECT_CALL()\fP\fP statement evaluates the action clause only once, even though the action may be performed many times\&. Therefore you must be careful about side effects\&. The following may not do what you want:
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
int n = 100;
EXPECT_CALL(turtle, GetX())
    \&.Times(4)
    \&.WillRepeatedly(Return(n++));
.fi
.PP
.PP
Instead of returning 100, 101, 102, \&.\&.\&., consecutively, this mock function will always return 100 as \fCn++\fP is only evaluated once\&. Similarly, \fCReturn(new Foo)\fP will create a new \fCFoo\fP object when the \fC\fBEXPECT_CALL()\fP\fP is executed, and will return the same pointer every time\&. If you want the side effect to happen every time, you need to define a custom action, which we'll teach in the \fBcook book\fP\&.
.PP
Time for another quiz! What do you think the following means?
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
EXPECT_CALL(turtle, GetY())
    \&.Times(4)
    \&.WillOnce(Return(100));
.fi
.PP
.PP
Obviously \fCturtle\&.GetY()\fP is expected to be called four times\&. But if you think it will return 100 every time, think twice! Remember that one \fC\fBWillOnce()\fP\fP clause will be consumed each time the function is invoked and the default action will be taken afterwards\&. So the right answer is that \fCturtle\&.GetY()\fP will return 100 the first time, but \fBreturn 0 from the second time on\fP, as returning 0 is the default action for \fCint\fP functions\&.
.SS "Using Multiple Expectations"
So far we've only shown examples where you have a single expectation\&. More realistically, you'll specify expectations on multiple mock methods which may be from multiple mock objects\&.
.PP
By default, when a mock method is invoked, gMock will search the expectations in the \fBreverse order\fP they are defined, and stop when an active expectation that matches the arguments is found (you can think of it as 'newer rules override
older ones\&.')\&. If the matching expectation cannot take any more calls, you will get an upper-bound-violated failure\&. Here's an example:
.PP
.PP
.nf
using ::testing::_;
\&.\&.\&.
EXPECT_CALL(turtle, Forward(_));  // #1
EXPECT_CALL(turtle, Forward(10))  // #2
    \&.Times(2);
.fi
.PP
.PP
If \fCForward(10)\fP is called three times in a row, the third time it will be an error, as the last matching expectation (#2) has been saturated\&. If, however, the third \fCForward(10)\fP call is replaced by \fCForward(20)\fP, then it would be OK, as now #1 will be the matching expectation\&.
.PP
{: \&.callout \&.note} \fBNote:\fP Why does gMock search for a match in the \fIreverse\fP order of the expectations? The reason is that this allows a user to set up the default expectations in a mock object's constructor or the test fixture's set-up phase and then customize the mock by writing more specific expectations in the test body\&. So, if you have two expectations on the same method, you want to put the one with more specific matchers \fBafter\fP the other, or the more specific rule would be shadowed by the more general one that comes after it\&.
.PP
{: \&.callout \&.tip} \fBTip:\fP It is very common to start with a catch-all expectation for a method and \fCTimes(AnyNumber())\fP (omitting arguments, or with \fC_\fP for all arguments, if overloaded)\&. This makes any calls to the method expected\&. This is not necessary for methods that are not mentioned at all (these are 'uninteresting'), but is useful for methods that have some expectations, but for which other calls are ok\&. See \fCUnderstanding Uninteresting vs Unexpected Calls\fP\&.
.SS "Expecting Ordered Calls"
By default, an expectation can match a call even though an earlier expectation hasn't been satisfied\&. In other words, the calls don't have to occur in the order the expectations are specified\&.
.PP
Sometimes, you may want all the expected calls to occur in a strict order\&. To say this in gMock is easy:
.PP
.PP
.nf
using ::testing::InSequence;
\&.\&.\&.
TEST(FooTest, DrawsLineSegment) {
  \&.\&.\&.
  {
    InSequence seq;

    EXPECT_CALL(turtle, PenDown());
    EXPECT_CALL(turtle, Forward(100));
    EXPECT_CALL(turtle, PenUp());
  }
  Foo();
}
.fi
.PP
.PP
By creating an object of type \fCInSequence\fP, all expectations in its scope are put into a \fIsequence\fP and have to occur \fIsequentially\fP\&. Since we are just relying on the constructor and destructor of this object to do the actual work, its name is really irrelevant\&.
.PP
In this example, we test that \fCFoo()\fP calls the three expected functions in the order as written\&. If a call is made out-of-order, it will be an error\&.
.PP
(What if you care about the relative order of some of the calls, but not all of them? Can you specify an arbitrary partial order? The answer is \&.\&.\&. yes! The details can be found \fChere\fP\&.)
.SS "All Expectations Are Sticky (Unless Said Otherwise)"
Now let's do a quick quiz to see how well you can use this mock stuff already\&. How would you test that the turtle is asked to go to the origin \fIexactly twice\fP (you want to ignore any other instructions it receives)?
.PP
After you've come up with your answer, take a look at ours and compare notes (solve it yourself first - don't cheat!):
.PP
.PP
.nf
using ::testing::_;
using ::testing::AnyNumber;
\&.\&.\&.
EXPECT_CALL(turtle, GoTo(_, _))  // #1
     \&.Times(AnyNumber());
EXPECT_CALL(turtle, GoTo(0, 0))  // #2
     \&.Times(2);
.fi
.PP
.PP
Suppose \fCturtle\&.GoTo(0, 0)\fP is called three times\&. In the third time, gMock will see that the arguments match expectation #2 (remember that we always pick the last matching expectation)\&. Now, since we said that there should be only two such calls, gMock will report an error immediately\&. This is basically what we've told you in the \fCUsing Multiple Expectations\fP section above\&.
.PP
This example shows that \fBexpectations in gMock are 'sticky' by default\fP, in the sense that they remain active even after we have reached their invocation upper bounds\&. This is an important rule to remember, as it affects the meaning of the spec, and is \fBdifferent\fP to how it's done in many other mocking frameworks (Why'd we do that? Because we think our rule makes the common cases easier to express and understand\&.)\&.
.PP
Simple? Let's see if you've really understood it: what does the following code say?
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
for (int i = n; i > 0; i--) {
  EXPECT_CALL(turtle, GetX())
      \&.WillOnce(Return(10*i));
}
.fi
.PP
.PP
If you think it says that \fCturtle\&.GetX()\fP will be called \fCn\fP times and will return 10, 20, 30, \&.\&.\&., consecutively, think twice! The problem is that, as we said, expectations are sticky\&. So, the second time \fCturtle\&.GetX()\fP is called, the last (latest) \fC\fBEXPECT_CALL()\fP\fP statement will match, and will immediately lead to an 'upper bound violated' error - this piece of code is not very useful!
.PP
One correct way of saying that \fCturtle\&.GetX()\fP will return 10, 20, 30, \&.\&.\&., is to explicitly say that the expectations are \fInot\fP sticky\&. In other words, they should \fIretire\fP as soon as they are saturated:
.PP
.PP
.nf
using ::testing::Return;
\&.\&.\&.
for (int i = n; i > 0; i--) {
  EXPECT_CALL(turtle, GetX())
      \&.WillOnce(Return(10*i))
      \&.RetiresOnSaturation();
}
.fi
.PP
.PP
And, there's a better way to do it: in this case, we expect the calls to occur in a specific order, and we line up the actions to match the order\&. Since the order is important here, we should make it explicit using a sequence:
.PP
.PP
.nf
using ::testing::InSequence;
using ::testing::Return;
\&.\&.\&.
{
  InSequence s;

  for (int i = 1; i <= n; i++) {
    EXPECT_CALL(turtle, GetX())
        \&.WillOnce(Return(10*i))
        \&.RetiresOnSaturation();
  }
}
.fi
.PP
.PP
By the way, the other situation where an expectation may \fInot\fP be sticky is when it's in a sequence - as soon as another expectation that comes after it in the sequence has been used, it automatically retires (and will never be used to match any call)\&.
.SS "Uninteresting Calls"
A mock object may have many methods, and not all of them are that interesting\&. For example, in some tests we may not care about how many times \fCGetX()\fP and \fCGetY()\fP get called\&.
.PP
In gMock, if you are not interested in a method, just don't say anything about it\&. If a call to this method occurs, you'll see a warning in the test output, but it won't be a failure\&. This is called 'naggy' behavior; to change, see \fCThe Nice, the Strict, and the Naggy\fP\&. 
