.TH "MissingDebugStringMethod" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MissingDebugStringMethod
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBDebugString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7199 of file gtest_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string MissingDebugStringMethod::DebugString ()\fC [inline]\fP"

.PP
Definition at line 7200 of file gtest_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
