.TH "MockFoo" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockFoo
.SH SYNOPSIS
.br
.PP
.PP
Inherits FooInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMockFoo\fP ()=default"
.br
.ti -1c
.RI "\fBMOCK_METHOD3\fP (Bar, char(const std::string &s, int \fBi\fP, double \fBx\fP))"
.br
.ti -1c
.RI "\fBMOCK_METHOD2\fP (Bar2, bool(int \fBx\fP, int \fBy\fP))"
.br
.ti -1c
.RI "\fBMOCK_METHOD2\fP (Bar3, void(int \fBx\fP, int \fBy\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file gmock_output_test_\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MockFoo::MockFoo ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "MockFoo::MOCK_METHOD2 (Bar2, bool(int \fBx\fP, int \fBy\fP))"

.SS "MockFoo::MOCK_METHOD2 (Bar3, void(int \fBx\fP, int \fBy\fP))"

.SS "MockFoo::MOCK_METHOD3 (Bar, char(const std::string &s, int \fBi\fP, double \fBx\fP))"


.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
