.TH "MyArray< T, kSize >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyArray< T, kSize >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T, int kSize>
.br
class MyArray< T, kSize >"

.PP
Definition at line 111 of file googletest\-list\-tests\-unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
