.TH "MyType" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyType\fP (const std::string &a_value)"
.br
.ti -1c
.RI "const std::string & \fBvalue\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file googletest\-list\-tests\-unittest_\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyType::MyType (const std::string & a_value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 71 of file googletest\-list\-tests\-unittest_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::string& MyType::value () const\fC [inline]\fP"

.PP
Definition at line 73 of file googletest\-list\-tests\-unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
