.TH "NonDefaultConstructAssignString" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonDefaultConstructAssignString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonDefaultConstructAssignString\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBNonDefaultConstructAssignString\fP ()=delete"
.br
.ti -1c
.RI "\fBNonDefaultConstructAssignString\fP (const \fBNonDefaultConstructAssignString\fP &)=default"
.br
.ti -1c
.RI "\fBNonDefaultConstructAssignString\fP & \fBoperator=\fP (const \fBNonDefaultConstructAssignString\fP &)=delete"
.br
.ti -1c
.RI "\fB~NonDefaultConstructAssignString\fP ()=default"
.br
.ti -1c
.RI "const std::string & \fBstr\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 485 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NonDefaultConstructAssignString::NonDefaultConstructAssignString (const std::string & s)\fC [inline]\fP"

.PP
Definition at line 487 of file googletest\-param\-test\-test\&.cc\&.
.SS "NonDefaultConstructAssignString::NonDefaultConstructAssignString ()\fC [delete]\fP"

.SS "NonDefaultConstructAssignString::NonDefaultConstructAssignString (const \fBNonDefaultConstructAssignString\fP &)\fC [default]\fP"

.SS "NonDefaultConstructAssignString::~NonDefaultConstructAssignString ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBNonDefaultConstructAssignString\fP& NonDefaultConstructAssignString::operator= (const \fBNonDefaultConstructAssignString\fP &)\fC [delete]\fP"

.SS "const std::string& NonDefaultConstructAssignString::str () const\fC [inline]\fP"

.PP
Definition at line 495 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
