.TH "NonFatalFailureInSetUpTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonFatalFailureInSetUpTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB~NonFatalFailureInSetUpTest\fP () override"
.br
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 413 of file googletest\-output\-test_\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NonFatalFailureInSetUpTest::~NonFatalFailureInSetUpTest ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 415 of file googletest\-output\-test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void NonFatalFailureInSetUpTest::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 417 of file googletest\-output\-test_\&.cc\&.
.SS "void NonFatalFailureInSetUpTest::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 422 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
