.TH "NonParameterizedBaseTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonParameterizedBaseTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.PP
Inherited by \fBParameterizedDerivedTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNonParameterizedBaseTest\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBn_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1078 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NonParameterizedBaseTest::NonParameterizedBaseTest ()\fC [inline]\fP"

.PP
Definition at line 1080 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int NonParameterizedBaseTest::n_\fC [protected]\fP"

.PP
Definition at line 1083 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
