.TH "ParamTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestWithParam< int >\fP, and \fBtesting::TestWithParam< std::string >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 679 of file googletest\-output\-test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
