.TH "ParameterizedDerivedTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParameterizedDerivedTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNonParameterizedBaseTest\fP, and \fBtesting::WithParamInterface< int >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterizedDerivedTest\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBcount_\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fBglobal_count_\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1086 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParameterizedDerivedTest::ParameterizedDerivedTest ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 1089 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int ParameterizedDerivedTest::count_\fC [protected]\fP"

.PP
Definition at line 1090 of file googletest\-param\-test\-test\&.cc\&.
.SS "int ParameterizedDerivedTest::global_count_ = 0\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1091 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
