.TH "ParameterizedDeathTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParameterizedDeathTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestWithParam< int >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1104 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
