.TH "ParentClass" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParentClass
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBChildClassWithStreamOperator\fP, and \fBChildClassWithoutStreamOperator\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 92 of file googletest\-printers\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
