.TH "PreCalculatedPrimeTable" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreCalculatedPrimeTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prime_tables\&.h>\fP
.PP
Inherits \fBPrimeTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreCalculatedPrimeTable\fP (int max)"
.br
.ti -1c
.RI "\fB~PreCalculatedPrimeTable\fP () override"
.br
.ti -1c
.RI "bool \fBIsPrime\fP (int n) const override"
.br
.ti -1c
.RI "int \fBGetNextPrime\fP (int \fBp\fP) const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file prime_tables\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PreCalculatedPrimeTable::PreCalculatedPrimeTable (int max)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 80 of file prime_tables\&.h\&.
.SS "PreCalculatedPrimeTable::~PreCalculatedPrimeTable ()\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 85 of file prime_tables\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int PreCalculatedPrimeTable::GetNextPrime (int p) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrimeTable\fP\&.
.PP
Definition at line 91 of file prime_tables\&.h\&.
.SS "bool PreCalculatedPrimeTable::IsPrime (int n) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrimeTable\fP\&.
.PP
Definition at line 87 of file prime_tables\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
