.TH "Predicate5Test" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Predicate5Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static bool \fBexpected_to_finish_\fP"
.br
.ti -1c
.RI "static bool \fBfinished_\fP"
.br
.ti -1c
.RI "static int \fBn1_\fP"
.br
.ti -1c
.RI "static int \fBn2_\fP"
.br
.ti -1c
.RI "static int \fBn3_\fP"
.br
.ti -1c
.RI "static int \fBn4_\fP"
.br
.ti -1c
.RI "static int \fBn5_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1699 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void Predicate5Test::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 1701 of file gtest_pred_impl_unittest\&.cc\&.
.SS "void Predicate5Test::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 1707 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Predicate5Test::expected_to_finish_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1731 of file gtest_pred_impl_unittest\&.cc\&.
.SS "bool Predicate5Test::finished_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1734 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate5Test::n1_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1736 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate5Test::n2_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1737 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate5Test::n3_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1738 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate5Test::n4_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1739 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate5Test::n5_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1740 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
