.TH "PredFormatFunctor1" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredFormatFunctor1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 > testing::AssertionResult \fBoperator()\fP (const char *e1, const T1 &v1) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 > testing::AssertionResult PredFormatFunctor1::operator() (const char * e1, const T1 & v1) const\fC [inline]\fP"

.PP
Definition at line 104 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
