.TH "Predicate4Test" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Predicate4Test
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static bool \fBexpected_to_finish_\fP"
.br
.ti -1c
.RI "static bool \fBfinished_\fP"
.br
.ti -1c
.RI "static int \fBn1_\fP"
.br
.ti -1c
.RI "static int \fBn2_\fP"
.br
.ti -1c
.RI "static int \fBn3_\fP"
.br
.ti -1c
.RI "static int \fBn4_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1280 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void Predicate4Test::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 1282 of file gtest_pred_impl_unittest\&.cc\&.
.SS "void Predicate4Test::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 1288 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Predicate4Test::expected_to_finish_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1310 of file gtest_pred_impl_unittest\&.cc\&.
.SS "bool Predicate4Test::finished_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1313 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate4Test::n1_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1315 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate4Test::n2_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1316 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate4Test::n3_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1317 of file gtest_pred_impl_unittest\&.cc\&.
.SS "int Predicate4Test::n4_\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 1318 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
