.TH "PredFormatFunctor4" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredFormatFunctor4
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 > testing::AssertionResult \fBoperator()\fP (const char *e1, const char *e2, const char *e3, const char *e4, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1268 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 > testing::AssertionResult PredFormatFunctor4::operator() (const char * e1, const char * e2, const char * e3, const char * e4, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4) const\fC [inline]\fP"

.PP
Definition at line 1270 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
