.TH "PredFunctor4" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredFunctor4
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 > bool \fBoperator()\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1246 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 > bool PredFunctor4::operator() (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)\fC [inline]\fP"

.PP
Definition at line 1248 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
