.TH "PredFunctor1" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredFunctor1
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 > bool \fBoperator()\fP (const T1 &v1)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file gtest_pred_impl_unittest\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 > bool PredFunctor1::operator() (const T1 & v1)\fC [inline]\fP"

.PP
Definition at line 87 of file gtest_pred_impl_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
