.TH "PrimeTable" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrimeTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prime_tables\&.h>\fP
.PP
Inherited by \fBOnTheFlyPrimeTable\fP, and \fBPreCalculatedPrimeTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PrimeTable\fP ()=default"
.br
.ti -1c
.RI "virtual bool \fBIsPrime\fP (int n) const =0"
.br
.ti -1c
.RI "virtual int \fBGetNextPrime\fP (int \fBp\fP) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file prime_tables\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual PrimeTable::~PrimeTable ()\fC [virtual]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual int PrimeTable::GetNextPrime (int p) const\fC [pure virtual]\fP"

.PP
Implemented in \fBPreCalculatedPrimeTable\fP, and \fBOnTheFlyPrimeTable\fP\&.
.SS "virtual bool PrimeTable::IsPrime (int n) const\fC [pure virtual]\fP"

.PP
Implemented in \fBPreCalculatedPrimeTable\fP, and \fBOnTheFlyPrimeTable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
