.TH "build/_deps/googletest-src/googletest/samples/prime_tables.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/samples/prime_tables.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrimeTable\fP"
.br
.ti -1c
.RI "class \fBOnTheFlyPrimeTable\fP"
.br
.ti -1c
.RI "class \fBPreCalculatedPrimeTable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
