.TH "PrivateCode" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrivateCode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <production\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFRIEND_TEST\fP (PrivateCodeTest, CanAccessPrivateMembers)"
.br
.ti -1c
.RI "\fBFRIEND_TEST\fP (\fBPrivateCodeFixtureTest\fP, CanAccessPrivateMembers)"
.br
.ti -1c
.RI "\fBPrivateCode\fP ()"
.br
.ti -1c
.RI "int \fBx\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file production\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PrivateCode::PrivateCode ()"

.PP
Definition at line 35 of file production\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "PrivateCode::FRIEND_TEST (\fBPrivateCodeFixtureTest\fP, CanAccessPrivateMembers)"

.SS "PrivateCode::FRIEND_TEST (PrivateCodeTest, CanAccessPrivateMembers)"

.SS "int PrivateCode::x () const\fC [inline]\fP"

.PP
Definition at line 48 of file production\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
