.TH "PropertyRecordingTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertyRecordingTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file gtest_xml_output_unittest_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "static void PropertyRecordingTest::SetUpTestSuite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 115 of file gtest_xml_output_unittest_\&.cc\&.
.SS "static void PropertyRecordingTest::TearDownTestSuite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 116 of file gtest_xml_output_unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
