.TH "PropertyTwo" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertyTwo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 37 of file gtest_xml_outfile2_test_\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void PropertyTwo::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 39 of file gtest_xml_outfile2_test_\&.cc\&.
.SS "void PropertyTwo::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 40 of file gtest_xml_outfile2_test_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
