.TH "QueueNode< E >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueNode< E >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sample3\-inl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const E & \fBelement\fP () const"
.br
.ti -1c
.RI "\fBQueueNode\fP * \fBnext\fP ()"
.br
.ti -1c
.RI "const \fBQueueNode\fP * \fBnext\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQueue< E >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename E>
.br
class QueueNode< E >"

.PP
Definition at line 46 of file sample3\-inl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename E > const E& \fBQueueNode\fP< E >::element () const\fC [inline]\fP"

.PP
Definition at line 51 of file sample3\-inl\&.h\&.
.SS "template<typename E > \fBQueueNode\fP* \fBQueueNode\fP< E >::next ()\fC [inline]\fP"

.PP
Definition at line 54 of file sample3\-inl\&.h\&.
.SS "template<typename E > const \fBQueueNode\fP* \fBQueueNode\fP< E >::next () const\fC [inline]\fP"

.PP
Definition at line 55 of file sample3\-inl\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename E > friend class \fBQueue\fP< E >\fC [friend]\fP"

.PP
Definition at line 1 of file sample3\-inl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
