.TH "build/_deps/googletest-src/googletest/samples/sample1.h" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/samples/sample1.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBFactorial\fP (int n)"
.br
.ti -1c
.RI "bool \fBIsPrime\fP (int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Factorial (int n)"

.PP
Definition at line 35 of file sample1\&.cc\&.
.SS "bool IsPrime (int n)"

.PP
Definition at line 45 of file sample1\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
