.TH "build/_deps/googletest-src/googletest/samples/sample5_unittest.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/samples/sample5_unittest.cc
.SH SYNOPSIS
.br
.PP
\fC#include <limits\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'sample1\&.h'\fP
.br
\fC#include 'sample3\-inl\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
