.TH "build/_deps/googletest-src/googletest/samples/sample2_unittest.cc" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/_deps/googletest-src/googletest/samples/sample2_unittest.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'sample2\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
