.TH "SeparateInstanceTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeparateInstanceTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestWithParam< int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSeparateInstanceTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBcount_\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int \fBglobal_count_\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 807 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SeparateInstanceTest::SeparateInstanceTest ()\fC [inline]\fP"

.PP
Definition at line 809 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "static void SeparateInstanceTest::TearDownTestSuite ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 811 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int SeparateInstanceTest::count_\fC [protected]\fP"

.PP
Definition at line 820 of file googletest\-param\-test\-test\&.cc\&.
.SS "int SeparateInstanceTest::global_count_ = 0\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 821 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
