.TH "StatefulNamingFunctor" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatefulNamingFunctor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatefulNamingFunctor\fP ()"
.br
.ti -1c
.RI "std::string \fBoperator()\fP (const ::\fBtesting::TestParamInfo\fP< int > &info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1020 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatefulNamingFunctor::StatefulNamingFunctor ()\fC [inline]\fP"

.PP
Definition at line 1021 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string StatefulNamingFunctor::operator() (const ::\fBtesting::TestParamInfo\fP< int > & info)\fC [inline]\fP"

.PP
Definition at line 1022 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int StatefulNamingFunctor::sum"

.PP
Definition at line 1027 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
