.TH "StatefulNamingTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatefulNamingTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestWithParam< int >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBStatefulNamingTest\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBsum_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1030 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatefulNamingTest::StatefulNamingTest ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 1032 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int StatefulNamingTest::sum_\fC [protected]\fP"

.PP
Definition at line 1033 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
