.TH "StreamableInGlobal" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamableInGlobal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~StreamableInGlobal\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file googletest\-printers\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual StreamableInGlobal::~StreamableInGlobal ()\fC [virtual]\fP, \fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
