.TH "SuccessfulTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuccessfulTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SH "Detailed Description"
.PP 
Definition at line 51 of file gtest_xml_output_unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
