.TH "TestGenerationEnvironment< kExpectedCalls >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestGenerationEnvironment< kExpectedCalls >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Environment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFixtureConstructorExecuted\fP ()"
.br
.ti -1c
.RI "void \fBSetUpExecuted\fP ()"
.br
.ti -1c
.RI "void \fBTearDownExecuted\fP ()"
.br
.ti -1c
.RI "void \fBTestBodyExecuted\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTestGenerationEnvironment\fP * \fBInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int kExpectedCalls>
.br
class TestGenerationEnvironment< kExpectedCalls >"

.PP
Definition at line 607 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int kExpectedCalls> void \fBTestGenerationEnvironment\fP< kExpectedCalls >::FixtureConstructorExecuted ()\fC [inline]\fP"

.PP
Definition at line 614 of file googletest\-param\-test\-test\&.cc\&.
.SS "template<int kExpectedCalls> static \fBTestGenerationEnvironment\fP* \fBTestGenerationEnvironment\fP< kExpectedCalls >::Instance ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 609 of file googletest\-param\-test\-test\&.cc\&.
.SS "template<int kExpectedCalls> void \fBTestGenerationEnvironment\fP< kExpectedCalls >::SetUpExecuted ()\fC [inline]\fP"

.PP
Definition at line 615 of file googletest\-param\-test\-test\&.cc\&.
.SS "template<int kExpectedCalls> void \fBTestGenerationEnvironment\fP< kExpectedCalls >::TearDown ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Environment\fP\&.
.PP
Definition at line 619 of file googletest\-param\-test\-test\&.cc\&.
.SS "template<int kExpectedCalls> void \fBTestGenerationEnvironment\fP< kExpectedCalls >::TearDownExecuted ()\fC [inline]\fP"

.PP
Definition at line 616 of file googletest\-param\-test\-test\&.cc\&.
.SS "template<int kExpectedCalls> void \fBTestGenerationEnvironment\fP< kExpectedCalls >::TestBodyExecuted ()\fC [inline]\fP"

.PP
Definition at line 617 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
