.TH "TestingVector" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestingVector
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::vector< int >\&.
.SH "Detailed Description"
.PP 
Definition at line 289 of file gtest_unittest\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
