.TH "ThrowListener" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::EmptyTestEventListener\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 40 of file gtest_assert_by_exception_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
