.TH "TypeParametrizedTestWithNames< T >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeParametrizedTestWithNames< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class TypeParametrizedTestWithNames< T >"

.PP
Definition at line 292 of file gtest\-typed\-test_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
