.TH "TypedTest< T >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypedTest< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test, \fBtesting::Test\fP, \fBtesting::Test\fP, \fBtesting::Test\fP, and Test\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class TypedTest< T >"

.PP
Definition at line 108 of file googletest\-list\-tests\-unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
