.TH "TypeParameterizedTestSuite< T >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeParameterizedTestSuite< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP, and Test\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class TypeParameterizedTestSuite< T >"

.PP
Definition at line 64 of file gtest_list_output_unittest_\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
