.TH "TypeParametrizedTestNames" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypeParametrizedTestNames
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static std::string \fBGetName\fP (int \fBi\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 313 of file gtest\-typed\-test_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static std::string TypeParametrizedTestNames::GetName (int i)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 316 of file gtest\-typed\-test_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
