.TH "TypedTestSuitePStateTest" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TypedTestSuitePStateTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "TypedTestSuitePState \fBstate_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 200 of file gtest\-typed\-test_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void TypedTestSuitePStateTest::SetUp ()\fC [inline]\fP, \fC [override]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtesting::Test\fP\&.
.PP
Definition at line 202 of file gtest\-typed\-test_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "TypedTestSuitePState TypedTestSuitePStateTest::state_\fC [protected]\fP"

.PP
Definition at line 208 of file gtest\-typed\-test_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
