.TH "UnprintableTemplateInGlobal< T >" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnprintableTemplateInGlobal< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnprintableTemplateInGlobal\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class UnprintableTemplateInGlobal< T >"

.PP
Definition at line 104 of file googletest\-printers\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBUnprintableTemplateInGlobal\fP< T >::\fBUnprintableTemplateInGlobal\fP ()\fC [inline]\fP"

.PP
Definition at line 106 of file googletest\-printers\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
