.TH "Unstreamable" 3 "Tue Sep 12 2023" "Week2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unstreamable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnstreamable\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "const int & \fBdummy_value\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1052 of file googletest\-param\-test\-test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Unstreamable::Unstreamable (int value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 1054 of file googletest\-param\-test\-test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "const int& Unstreamable::dummy_value () const\fC [inline]\fP"

.PP
Definition at line 1056 of file googletest\-param\-test\-test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Week2 from the source code\&.
